### ISSUE TITLE
Feature Request: Min and Max Temp for Area

### ISSUE THREAD

**Issue by mwolter805** [jseidl/hass-magic_areas#102]
Hello, one “fun” thing I like to display in Lovelace and is related to areas is the min and max temp for the area. For instance it’s nice to see how cold or hot an inside (garage, living room, bedroom, etc.) or outside (porch, backyard, etc.) area has been for the past day. Appears this could be a good feature to add to the area temp aggregation average while making the period configurable, for instance, the past day. 

Currently I am doing this using the statistics component but was thinking this is directly related to areas and is something many people would be interested in using for each area of the house, adding this to Magic Areas seems like a good fit and would help reduce the complexity of my configuration file. 

Along these lines, another “fun” thing would be a temp state indicating the current temp trend (if the temp is rising, lowering or remaining constant). This could be used to display an icon in Lovelace showing the direction the temperature is trending at the moment.

**Comment by KTibow** [comment]
Seems more like historic data, meant for another component IMO.

**Comment by jseidl** [comment]
This would be difficult on the current architecture of Magic Areas as it has to be able to handle all different `device_class`es.

One workaround would be to use [History Graph](https://www.home-assistant.io/lovelace/history-graph/) cards to have a quick glance of trends and mix/max.
