### ISSUE TITLE
Setup failed for magic_areas: Integration 'magic_areas' did not return boolean if setup was successful. Disabling component.

### ISSUE THREAD

**Issue by mifbody** [jseidl/hass-magic_areas#107]
Installed Magic Areas through HACS, rebooted Home Assistant. Added the magic_areas flag into configuration.yaml and I receive the following notification upon rebooting:

"Setup failed for magic_areas: Integration 'magic_areas' did not return boolean if setup was successful. Disabling component."

Home Assistant OS 5.12, core-2021.3.4, supervisor-2021.03.6

**Comment by jseidl** [comment]
Thanks for reporting, will investigate

**Comment by jseidl** [comment]
@mifbody I wasn't able to reproduce, are you still experiencing this issue?

**Comment by jseidl** [comment]
Closing as stale. If you still have the issue please reopen.
