### ISSUE TITLE
Removing a no longer present entity

### ISSUE THREAD

**Issue by atmezferix** [jseidl/hass-magic_areas#110]
I had a light entity excluded from Magic Areas as it was not really a light but a switch that was wrongly categorised by ZHA.

I've corrected that issue now and it is in the switch domain but the issue I have is I can no remove it from the Excluded area as the list is populated only from available entities and not over writable in the text box.

Would it be possible to maybe have a cross next to it so it could be removed or some other method of removing ?

It means whilst that is still there I'm unable to make any changes to its configuration as it comes up with an error when trying to save.

**Comment by TheArcturian** [comment]
Would be great to have a release just with this bug corrected.

**Comment by jseidl** [comment]
Possibly related to #95

**Comment by jseidl** [comment]
Closing as it's a duplicate from #95 and being fixed by PR https://github.com/jseidl/hass-magic_areas/pull/118
