### ISSUE TITLE
[Support-Request] Shelly - Yeelight - Aqara Motion

### ISSUE THREAD

**Issue by b2az** [jseidl/hass-magic_areas#115]
Hi dudes/dudettes,

Thanks for this integration i've allready read the blog on synapselabs.
I'm trying to bring my current setup together with this integration as final step.

Setup:
So there are lightswitches (actually buttons - only on when pressed) with Shelly1 connected to them.
The shelly devices are configured for button-usage and are connected to the HA-Mosquitto Addon.
In combination with the ha-shellies-discovery script [(script)](https://github.com/bieniu/ha-shellies-discovery) i get the following relevant entities:

- binary_sensor.shelly1_xyzxyz_input_0 
- binary_sensor.shelly1_xyzxyz_longpush_0
- light.shelly1_xyzxyz_relay_0
- binary_sensor.shelly_1_xyzxyz_shortpush_0

All lights in the entire room are Yeelight products (stripe, ceiling20, ceiling10, color)
The strip and RGB-bulb are pretty straightforward, they offer only one light entity.
Different story with the ceiling lights (YLXD50YL). Here we have for each device:
 - light.ceiling_light ( mainlight and ambilight )
 - light.ceiling_light_ambilight ( only ambilight )
 - binary_sensor.ceiling_light_nightlight ( corresponds with the next entity )
 - light.ceiling_light_nightlight ( mainlight 0.5% )

Right now i created automations for each room, which look like (pseudo code):
 - if *shortpush*: light.toggle light.ceiling_light
 - if *longpush*: light.toggle light.ceiling_light_ambilight
 - if *longpush* > 5s: vacuum.start_room_cleaning

The Brightness and Color of the light is already steered with the Circadian Lighting Integration [(integration)](https://github.com/claytonjn/hass-circadian_lighting)

So everything until here is working smoothly. WAF to the moon 🚀.

Now I'm tinkering with aqara motion sensors, which are connected with the Xiaomi Gateway V3.
Those are giving me following relevant entities:
 - sensor.0x158d000xyzxyz_illuminance - 61 lx
 - binary_sensor.0x158d000xyzxyz_motion - ['clear', 'detected']

Now to my questions:
How should i design my magic-areas configuration? Which entities should i include/exclude?
Will there be an illuminance setting with threshold in the future?
How should i proceed with my existing automations which toggle the lights?
Can you give me some hints?

Thank you very much in advance. Looking forward to:

> walk around like a ~~fucking god~~ king

**Comment by jseidl** [comment]
Hey @b2az thanks for the report! Documentation has been lacking and I'm working on getting this out this weekend.

Regarding your buttons setup, I don't think you need to change anything to adapt to MA. MA works on the concept of presence so you'll have to work with the aqara motion sensors to trigger the presence on the areas. If they have the one of the presence device classes (default: motion/presence -- more can be configured on the integration) they will automatically turn on/off the lights on that area. Just make sure to add those entities to the area in HA.

You can set which lights are your main_lights which will be turned on by MA. All lights gets turned off when the area is clear. You can exclude any presence sensor you don't want triggering presence or any light you don't want controlled.

> Will there be an illuminance setting with threshold in the future?
This is a planned feature https://github.com/jseidl/hass-magic_areas/issues/30

> Can you give me some hints?

I use the following as presence sensors:
* motion sensors
* inputs from AI person recognition on cameras 
* device_tracker for computers, tvs 
* smart outlets with power metering paired with template binary sensors

And lights i usually have it accent lights as sleep_lights and the ceiling lights as main_lights.

Let me know if those tips are helpful!

**Comment by jseidl** [comment]
Hey @b2az, gonna close this one since it has been a while.
