### ISSUE TITLE
adding remote device_class for presence detection

### ISSUE THREAD

**Issue by kotarokun** [jseidl/hass-magic_areas#117]
hello,

I came across your great project and try to implement this immediately. But now I have a problem that I noticed immediately in the living room and that is that devices of the class remote are not supported. Here it would be great, if a remote has the status on (like the Harmony Remote), that the presence would be triggered. Because as long as I have the TV on, I do not want to sit in the dark. 

Would this be possible?

**Comment by jseidl** [comment]
Hi @kotarokun, you'll need to create template sensors meanwhile. I'm adding this feature request to our backlog. Thanks for reporting!

**Comment by jseidl** [comment]
This is coming on `3.0.0` and already working on `3.0.0-beta`
