### ISSUE TITLE
Sensor uses deactivated entities

### ISSUE THREAD

**Issue by sti0** [jseidl/hass-magic_areas#12]
I have a mqtt discovered light which I deactivated, because the lamp contains multiple bulbs and I configured a light group instead. 
![image](https://user-images.githubusercontent.com/18382402/96504900-ab46dc00-1255-11eb-82d4-95b7ab18097e.png)
![image](https://user-images.githubusercontent.com/18382402/96504987-c9144100-1255-11eb-9b50-db3b836179cc.png)

The area sensor uses this deactivated entity:
![image](https://user-images.githubusercontent.com/18382402/96505057-e47f4c00-1255-11eb-85f4-9b99872a54fb.png)

**Comment by jseidl** [comment]
Thanks for reporting. Will look into it.

**Comment by jseidl** [comment]
Meanwhile, can you try setting this entity in `exclude_entities`?
