### ISSUE TITLE
disable_entity not found

### ISSUE THREAD

**Issue by kotarokun** [jseidl/hass-magic_areas#120]
Hello,

sorry for another Issue, but i can't find disable_entity in UI-Config for disabling light while lux is too high... 
Did i am be blind? or is there no disable_entity in UI like here seen:
https://github.com/jseidl/hass-magic_areas/issues/16#issuecomment-766322760

like you sad: https://github.com/jseidl/hass-magic_areas/issues/30#issuecomment-716129528 these ar the way to disable light from going on while it is to bright.

thanks for help.

**Comment by kotarokun** [comment]
Oh okay. I found it. It called night for now...
Maybe "Night" should be called "Light" so it is clear for standing for Light mode at day and night...

**Comment by jseidl** [comment]
It will be called `dark` actually, in a future release. Magic Areas work on a area-state premise, so when the area goes into a `dark` state (defined by an entity as currently), then automatic lights will work.

It's tricky to get the naming right but hopefully we'll get there!
