### ISSUE TITLE
Adding Web UI instead of integration setup menu

### ISSUE THREAD

**Issue by danhajduk** [jseidl/hass-magic_areas#121]
Hi,
I would like to start by saying a really love this integration.
I do find the integration menu a bit complicated and not very intuitive. 
I would like to propose a new feature to have it all in a web UI.
This will make it possible to expand the configurations and customization.

Again I really love this and thank you

**Comment by jseidl** [comment]
Thanks for the sweet comments! This is my first integration so I'm stumbling with getting the integrations menu right. It does looks cramped and cumbersome and hopefully on next major version release we'll have that sorted out.

Can you elaborate on the web ui idea?

**Comment by jseidl** [comment]
Hi, can you try out the code on the `3.0.0-beta` branch? (Or wait until the weekend for the next release). The Integration flow was totally rewritten and shall be much more intuitive. Also now we have a [wiki](https://github.com/jseidl/hass-magic_areas/wiki)!
