### ISSUE TITLE
Add device_class: battery of sensors to binary_sensor.area_battery_interior

### ISSUE THREAD

**Issue by klatka** [jseidl/hass-magic_areas#122]
Magic Areas creates a battery sensor `binary_sensor.area_battery_interior` populated with `binary_sensor.battery_low_battery` with `device_class: battery`.

There are also `sensor.battery_level_x` with `device_class: battery` that are ignored by `binary_sensor.area_battery_interior`.

Please add these sensors too.
Thank you!

**Comment by jseidl** [comment]
Hi, these are automatically grouped according to their device class. If the entity is not being picked up by `area_battery_interior` then it should have no area assigned to it (or more specifically, an `interior` area).

Can you check?

**Comment by klatka** [comment]
Interior area is assigned. `sensor.battery_level_x` are somehow ignored.

**Comment by jseidl** [comment]
Which area is `sensor.battery_level_x` in, in Home Assistant?

**Comment by klatka** [comment]
I have just learned that there is a `sensor.area_battery_interior` with all `sensor.battery_level_x (device class: battery)` and `binary_sensor.area_battery_interior` with `binary_sensor.battery_state`. These are just separated.
