### ISSUE TITLE
Integration settings do not pick up entity/device area changes until HA is restarted

### ISSUE THREAD

**Issue by sjthespian** [jseidl/hass-magic_areas#129]
I have noticed that if I change the area on a device and then try and use it in Magic Areas, the device does not appear in the drop-down list in the area configuration web UI. I haven't verified if this is only true if I have already edited the configuration for that area or if it will also occur the first time I look at a configuration after a restart.

An HA restart will cause the entity/device to appear in the configuration UI. I think it will also appear after a long period of time, but the one time I saw that I don't remember if I had also restarted HA in the meantime with a config change.

**Comment by jseidl** [comment]
This is expected. Area maps all the entities when it's created by Home Assistant (during integration start). If you edit the configuration for an area it will force that area to reload and then reload the new entities so the solution for using newly set entities is to either give a configuration change on the area or restart.

**Comment by jseidl** [comment]
Adding the `documentation` label as this information needs to go to the [Wiki](https://github.com/jseidl/hass-magic_areas/wiki)

**Comment by sjthespian** [comment]
Ok, that makes sense. Feel free to close this one out once the docs are updated.

**Comment by jseidl** [comment]
Doc updated at https://github.com/jseidl/hass-magic_areas/wiki/Area-State
