### ISSUE TITLE
Many warnings after startup

### ISSUE THREAD

**Issue by sti0** [jseidl/hass-magic_areas#13]
My zigbee2mqtt sensor's are not ready immediately after startup. Because of this the state is unknown. Magic areas floods the logs with convert warnings.

![image](https://user-images.githubusercontent.com/18382402/96510163-6757d500-125d-11eb-9c66-c7391d146971.png)

**Comment by jseidl** [comment]
This is a duplicate of #8 and will be fixed in the next release.
