### ISSUE TITLE
Make aggregates configurable by device_class

### ISSUE THREAD

**Issue by felix63** [jseidl/hass-magic_areas#133]
Hi,

Looks promising your solution. I am still exploring but I see that Magic Areas creates entities 'binary_sensor.area_battery_xxx' and 'sensor.area_battery_xxx'. Is there an option to turn this off other than manual excluding all battery related entities (to much work :-), for some areas this is in excess of 10 entities). Perhaps you can add this as a new feature.

**Comment by jseidl** [comment]
I believe the usefulness may vary by user, but having an option to specify which device_class you want aggregated will solve this use-case and be a cool overall enhancement of the feature. Thanks for the idea!

**Comment by felix63** [comment]
Is it an option to use the new entity_category to ignore diagnostic entities for instance?
