### ISSUE TITLE
Feature: Input multi-select boxes with editable text field same as HA inputs

### ISSUE THREAD

**Issue by Bodge-IT** [jseidl/hass-magic_areas#138]
The current multi-select boxes do not allow editing the resultant selections in the field.  This is common to most inputs multi-select inputs in HA certainly those in Automations.  This feature alone would make including/excluding elements a little more workable.

Thanks for all your great work...this extension really starting to take shape.

**Comment by Bodge-IT** [comment]
Maybe this request is the same as #90

**Comment by jseidl** [comment]
It is, closing as duplicate, please watch the other thread.
