### ISSUE TITLE
Feature request: Add "debug" attribute triggered behavior

### ISSUE THREAD

**Issue by sti0** [jseidl/hass-magic_areas#14]
This is a feature request. I'm testing your component and tried some configuration entries like the `sleep_entity` and the `disable_entity`. Maybe you could add an attribute like the `active_sensors` attribute which tells the user what's the reason a triggered action (e.g. lights turning on) is.

I expect to get the information if the "normal" behavior is triggered, the "sleep" behavior is triggered or nothing is triggered because of the disabled entity. This would make debugging much easier. On my tests I have to look for mutliple entities while I'm running around the house and trigger motion sensors. Maybe it's wise to add a configuration boolean to toggle the information on/off.

**Comment by jseidl** [comment]
Good one. Will add a disabled and sleep attributes in the sensor.

**Comment by jseidl** [comment]
Prolly better have a single attribute called `automatic_lights` and have it set to either `disabled`, `normal` or `sleep`.

This would require adding trackers to `sleep_entity` and `disable_entity` (if set) to update this attribute. Also `update_area` (called on `update_interval`) must have a check to update this info as well.

I'm thinking on one function like `update_autolight_status` which checks both entities and sets the attribute. This way this can be called from both `update_area` and the tracker callbacks.

_(this is mostly a note for myself)_

**Comment by jseidl** [comment]
Started working on that on this issue on the branch `[feature/automatic-lights-state-attribute](https://github.com/jseidl/hass-magic_areas/tree/feature/automatic-lights-state-attribute)`. Blindly coded, not tested yet.
