### ISSUE TITLE
Global not always detecting

### ISSUE THREAD

**Issue by Bodge-IT** [jseidl/hass-magic_areas#143]
Hi, I have an issue where Global is not being triggered when one of the inside rooms is.
I don't have any exclusions in that room or on Global.
The element that is triggering the room does have a customisation setting it to 'door' class so that I can use the "Door" option on selected sensor types for the room.

I do have a similar config for another sensor on another room and that works AFAIK.

Any suggestion?
I have tried deleting both the room and global and allowing fresh config...no change.

Feature: As an aside...is there a way to see what sensor(s) triggered the detection?  Would be nice to see that in attributes for the room.

**Comment by jseidl** [comment]
Hey @Bodge-IT , can you check if this was solved in the beta?

**Comment by Bodge-IT** [comment]
Hi @jseidl I have not seen a recurrence of this in my recent testing.
