### ISSUE TITLE
[3.0.0] Numeric comparisons for area dark state

### ISSUE THREAD

**Issue by cerebrate** [jseidl/hass-magic_areas#146]
I could write a bunch of template sensors to define "dark" for each area and produce binary sensors to use in this piece of the config, but it would be much easier to have the option of "if entity value is below _this_, then it's dark", seeing as most light sensors seem to give you illuminance in lux. And since magic_areas will give you a handy per-area illuminance aggregate anyway, it seems the next logical step, 😃

**Comment by jseidl** [comment]
I believe we're tracking this on #30, please close if it's the same

**Comment by cerebrate** [comment]
Looks similar enough to do the job, anyway.
