### ISSUE TITLE
Feature request: Lightlevel

### ISSUE THREAD

**Issue by sti0** [jseidl/hass-magic_areas#15]
Could you please add the ability to set a specific light level for automatic lights? I my opinion it should be implemented to pass the brightness level through a template sensor. The template sensor handels the brightness in dependence of time or other cases. 

In my use case at specific times the kitchen light should turn on in full brightness (e.g. for cooking) and on other time frames it should only be dimmed.

**Comment by jseidl** [comment]
This is out of the scope of this component since there are dedicated solutions for that. Please see https://github.com/jseidl/hass-magic_areas/issues/4
