### ISSUE TITLE
"User input malformed" when re-configuring interation

### ISSUE THREAD

**Issue by felix63** [jseidl/hass-magic_areas#150]
Can not edit options anymore since upgrading to core-2021.11.0. Multi-selects specifically doesn't work. Gives 'User input malformed'. Similar issue in other custom integrations, see[ https://github.com/basnijholt/adaptive-lighting/issues/213 ]( https://github.com/basnijholt/adaptive-lighting/issues/213 )

<img width="595" alt="Schermafbeelding 2021-11-05 om 01 01 52" src="https://user-images.githubusercontent.com/16501940/140436676-22d24095-cb10-4b19-a9f2-043c14e0898a.png">

## System Health

version | core-2021.11.0
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.11.0-37-generic
arch | x86_64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4747
Installed Version | 1.16.0
Stage | running
Available Repositories | 889
Installed Repositories | 41

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | failed to load: timeout

</details>

<details><summary>Lovelace</summary>

dashboards | 5
-- | --
resources | 28
views | 22
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by jseidl** [comment]
Yeah that's pretty unfortunate. Also some multi-selects became checkboxes... sigh... will work on this issue this Sunday.

**Comment by jseidl** [comment]
```
        vol.Optional(
            CONF_PRESENCE_DEVICE_PLATFORMS,
            default=DEFAULT_PRESENCE_DEVICE_PLATFORMS,
        ): cv.ensure_list,
        vol.Optional(
            CONF_PRESENCE_SENSOR_DEVICE_CLASS,
            default=DEFAULT_PRESENCE_DEVICE_SENSOR_CLASS,
        ): cv.ensure_list,
```

These two options are declared the same way and one renders as checkboxes and one as a multi select 🤷

**Comment by felix63** [comment]
Watching the launch party I remember hearing that depending on the number of items there would be a difference how a list would be shown. Could that be the case here?

**Comment by jseidl** [comment]
Hmmm, possibly. That sucks, the config menu will be a mess... sigh. Still investigating this issue.

**Comment by felix63** [comment]
Is related to [https://github.com/home-assistant/frontend/issues/10567](url)

**Comment by jseidl** [comment]
Seems to be resolved in latest HA Frontend update. Still would prefer a way to enforce selects instead of checkboxes.

**Comment by jseidl** [comment]
Spoke too soon. Worked when I first updated but now it's giving me the same error when I'm trying to update areas.

**Comment by jseidl** [comment]
Weird thing if you delete the area, restart and configure the area, it works fine. If you try to re-configure the area, it gives `User Input Malformed`. Need to dig further.

**Comment by jseidl** [comment]
Original bug seems to be partially fixed. Remainder seems related to https://github.com/home-assistant/frontend/issues/10608

**Comment by felix63** [comment]
Closing this one as it is being fixed frontend.
