### ISSUE TITLE
Illuminance rolling value

### ISSUE THREAD

**Issue by kotarokun** [jseidl/hass-magic_areas#151]
Hello, 

Is there an Chance for Illuminance Value to get an rolling value, like 2 or 3 Value or 1 or 2 minutes of values?

Because my value get some sudden Change of value and my light is going off an on again...
Like these picture
![Screenshot_20211105-164122_Home Assistant](https://user-images.githubusercontent.com/8899437/140538467-64f81697-843a-4092-8a25-346fa2cf74e3.jpg)

The time is good for value with different times of value per Minute. On the other hand is just the last 2 or 3 Value also a good alternative.

Thanks a lot.

**Comment by jseidl** [comment]
Currently this is not supported. Aggregate sensors only do a mean/sum of current value of all sensors and does not keep track of previous values. You'd need to use [statistics sensor](https://www.home-assistant.io/integrations/statistics/) for that then aggregate on those sensors.
