### ISSUE TITLE
Aborted

### ISSUE THREAD

**Issue by Johnwillliam** [jseidl/hass-magic_areas#152]
![image](https://user-images.githubusercontent.com/24995119/141988578-2e040550-610d-45d6-92b3-54a3efa1ef20.png)
Installed via HACS but I don't see it in my integrations. Tried adding it and it shows the notifcation shown.

**Comment by jseidl** [comment]
Hey John. You have to add `magic_areas:` to your configuration.yaml

**Comment by Johnwillliam** [comment]
Ahh thank you! I did add it but I guess I didn't restart... My bad, thanks for the response
