### ISSUE TITLE
Lights turning off even if Night & Sleep Mode is Disabled

### ISSUE THREAD

**Issue by scoobee81** [jseidl/hass-magic_areas#153]
Hi Team - Hopefully this can be clarified, or if i've missed something.

Magic Areas: 2.0.5
Home Assistant Core: core-2021.11.4

If both Night and Sleep entities are disabled, and any lights in the selected area are manually turned on, they will turn off after the configured time (ie 60s) after presence was detected.

Is this expected behaviour?

Steps:
1. Disable or Turn off Night Mode and Sleep Mode in an area
2. Manually turn a light on in same area as step 1
3. Trigger the motion or presence sensor in same area as step 1
4. Allow the configured time to elapse (ie 60s)
**Expected:** The light should stay on
**Actual:** Light Turns off after configured time

**Comment by scoobee81** [comment]
Found some documentation that stated that this is correct behaviour, so closing issue. https://synapselabs.io/posts/bring-home-assistant-area-to-life-with-magic-areas/

Would be a good feature to be able to disable fully.

**Comment by jseidl** [comment]
Hey, just saw it now. If you check the wiki you'll see the documentation for the `3.0.x` release which is on beta right now. You can test by consuming the `release/3.0.0` branch. Now you're able to fully disable automatic control as well as fine tune its operation

**Comment by scoobee81** [comment]
Thats great, happy to test the BETA. Just can't figure out how to install it. I'll keep looking, i've missed something probably.

**Comment by jseidl** [comment]
Go to https://github.com/jseidl/hass-magic_areas/tree/release/3.0.0-beta and click the green `Code` button and download as a Zip file. Then replace your `custom_components/magic_areas` folder with the one on the Zip file.
