### ISSUE TITLE
Confused Question and Slow Loading Query

### ISSUE THREAD

**Issue by thorrrr** [jseidl/hass-magic_areas#158]
Hey Jseidl
I have had this installed for 12 months and i have read the professionally written blog and Wiki but my poor brain does not grasp how it works.
Do you have any other blogs or examples on how you would use this in an example config format?
I use many other installs which most i fully understand but this for some reason is a mental block for me.

On a side note this install is taking 89 to 110 seconds to load which seems terribly slow. Is this normal for this integration?

**Comment by jseidl** [comment]
Hey @thorrrr, so sorry the documentation is not working for you. One thing that might have confused you is that the wiki is written for the upcoming 3.0.0 release which differs in some aspects from the current stable 2.x. The blog post is entirely on 2.x tho.

This integration is a bit unorthodox as the configuration has a bit on yaml and a the rest over the UI.

In your `configuration.yaml` you just need to add 
```
magic_areas:
```
and after that the integration will be officially "installed". Upon first restart, the integration will cycle through all Areas you have created in Home Assistant and create a `Magic Area` integration instance for it which you can manage through the UI.

> The following explanation is considering the [new 3.0.0-beta branch](https://github.com/jseidl/hass-magic_areas/tree/release/3.0.0-beta) as I've been testing it for months and don't really remember how the configuration looks like on the 2.x much but the concepts are the same

Magic Areas works with the concepts of features, which you can read as "plug-ins" which provide different functionality. Users can opt into which ones they want to enable. The configuration flow has an initial screen which you have a few basic area settings and the next one will be where you tie the [secondary states](https://github.com/jseidl/hass-magic_areas/wiki/Area-State#secondary-states) to arbitrary entity states from Home Assistant. These secondary states are used further in the features/plugins for different purposes (for example, the Automatic Light control aspect of the Light Groups feature requires an Area to have the `dark` secondary state).

All the configuration options have some explanation on the configuration UI, let me know what other questions you have that I can help answering.

PS: Yes it takes a while to load as several calculations are done for some features and also we have to wait for other integrations to be done so we can have a full list of entities to work with. I'm still on the "make it work" phase of building this integration and I do plan in the future on doing some profiling to enhance those load times.

**Comment by thorrrr** [comment]
HI Jan
Cheers for quick reply it is not your docs more my mental bock.
I have in my setup Dwaines Dashboard so i can use HA on a wall mount.
Part of that is setting up groups for each room 
I tried to think if your integration could be used but gave up as it didn’t get it .
Like i mentioned do you have few examples of how you use it in an automation so i can see it visually ?
I like what i read and it sounds like it helps a lot but it is not computing in my head :), I have asked other on Discord but they are a little stumped. I did look on Youtube to see if thee were anny guides but did not see any.

**Comment by jseidl** [comment]
The idea is that Magic Areas offloads a lot of automations through the feature system. For example, automation for turning lights on and off automatically are handled by the Light Group (3.x) / Light Control (2.x) feature and so on but you can create your own.

Whenever you first install, Magic Areas will create a binary sensor for the area that will track if an area is occupied or not via the presence sensors in that area. Here's an example of one of my Area's binary_sensor

![image](https://user-images.githubusercontent.com/283041/148261608-7d0f6e65-3c66-484d-bf92-a53b644e91f2.png)

As you can see, there's a lot of entities that are used as presence state. You could use this binary_sensor as a trigger for when you want to perform actions whenever the room is occupied or not. I also have views for each room as you have and I use the "Aggregates" feature to show the overall motion, temp and luminosity levels and so on

![image](https://user-images.githubusercontent.com/283041/148261817-f14d333d-e04b-4791-8b5f-69902392dc44.png)

Here's a shot of the aggregate sensor for temperature

![image](https://user-images.githubusercontent.com/283041/148261862-5e1fbf04-a972-401a-a234-7b75b103bef0.png)

Another feature (this one is on 3.x only) is the light groups and climate groups features that will automatically control lights and climate devices based on the occupancy status of an area

![image](https://user-images.githubusercontent.com/283041/148262026-196a28d6-8d85-410a-8392-f4f3d9d951ed.png)

On the top row you see the light groups created by Magic Areas (Overhead, Task etc)

Here's the "Area Climate" group which will turn on any climate device in the area after it has been occupied for a while and off when the room is clear.

![image](https://user-images.githubusercontent.com/283041/148262142-df542594-5c4b-4256-810a-1723a528d224.png)

Hope that helps, let me know if you have other questions

**Comment by thorrrr** [comment]
HI Jan
I have just installed Beta 3 to  try new features and everything in MR has broke all entities saying not available ?

**Comment by jseidl** [comment]
Did you got it from the releases tab or from the branch?

**Comment by thorrrr** [comment]
HI
I picked it from HACS i had show Beta ?

**Comment by jseidl** [comment]
Hmm that one might be slightly outdated. Lemme generate a new one

**Comment by thorrrr** [comment]
Logger: homeassistant.components.binary_sensor
Source: custom_components/magic_areas/binary_sensor.py:223
Integration: Binary Sensor (documentation, issues)
First occurred: 18:46:58 (44 occurrences)
Last logged: 18:47:00

Error adding entities for domain binary_sensor with platform magic_areas
Error while setting up magic_areas platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 613, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 747, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/magic_areas/binary_sensor.py", line 265, in async_added_to_hass
    await self._initialize()
  File "/config/custom_components/magic_areas/binary_sensor.py", line 290, in _initialize
    self.load_attributes()
  File "/config/custom_components/magic_areas/binary_sensor.py", line 223, in load_attributes
    for feature_name, opts in self.area.config.get(
AttributeError: 'list' object has no attribute 'items'

**Comment by thorrrr** [comment]
Logger: custom_components.magic_areas.media_player
Source: custom_components/magic_areas/media_player.py:114
Integration: Magic Areas (documentation, issues)
First occurred: 18:46:58 (1 occurrences)
Last logged: 18:46:58

No areas with media_player entities. Skipping creation of area-aware-media-player

**Comment by jseidl** [comment]
Anyway it will break you current install because the configuration has been changed, you'll need to remove all instances of the integration from HA through the configuration UI and restart to have them re-created. I'm generating a new beta release now

**Comment by thorrrr** [comment]
So do i just mark it as remove in HACS

**Comment by jseidl** [comment]
> 

Go to the integrations area on Home Assistant, you'll see something like this

![image](https://user-images.githubusercontent.com/283041/148272832-00b7b12c-36ae-4bed-9b6f-6f8053f2886a.png)

Then click the entry, then the dots button and select `Delete`

![image](https://user-images.githubusercontent.com/283041/148272898-ca6f735a-93cf-4b91-9b72-80d815ec9692.png)

Do this for all areas and restart. 

Once I get the new release out you can update through HACS and then get it to deleting and restarting

**Comment by thorrrr** [comment]
i have deleted all areas and it disappeared so i restarted. Please let me know when Beta is ready

**Comment by thorrrr** [comment]
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 19:02:32 (21 occurrences)
Last logged: 19:02:34

Entity binary_sensor.area_garden (<class 'custom_components.magic_areas.binary_sensor.AreaPresenceBinarySensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity binary_sensor.area_guest_bedroom_one (<class 'custom_components.magic_areas.binary_sensor.AreaPresenceBinarySensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity binary_sensor.area_global (<class 'custom_components.magic_areas.binary_sensor.AreaPresenceBinarySensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity binary_sensor.area_interior (<class 'custom_components.magic_areas.binary_sensor.AreaPresenceBinarySensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity binary_sensor.area_exterior (<class 'custom_components.magic_areas.binary_sensor.AreaPresenceBinarySensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by jseidl** [comment]
This is fixed on beta1, release is out https://github.com/jseidl/hass-magic_areas/releases/tag/3.0.0-beta1

**Comment by thorrrr** [comment]
Sorry for being thick how is it best to load this ?

**Comment by jseidl** [comment]
Don't need to remove it, just update with the beta1 whenever it pops up.

If you DO need to remove it here's how to do it: https://github.com/jseidl/hass-magic_areas/wiki/Uninstalling

**Comment by jseidl** [comment]
And thanks for testing out 3.x, it really helps and I understand it's quite a hassle to reconfigure the areas

**Comment by jseidl** [comment]
If you go to hacs > integrations > search for Magic Areas and click the more button, you can force to pull the latest beta1 by clicking "Update infromation" then the beta1 should become available for updating 

![image](https://user-images.githubusercontent.com/283041/148275543-77120eca-8123-4fcb-9348-b1d123c534de.png)

**Comment by thorrrr** [comment]
not sure what has happened none of my HACS intergrations are showing up on HACS page

**Comment by thorrrr** [comment]
See [here ](https://xbackbone.daddycloud.co.uk/Piqa4/zOxUBIse73.jpg)

**Comment by jseidl** [comment]
That is weird, I just updated Magic Areas through HACS to beta1 and it worked fine. 
![image](https://user-images.githubusercontent.com/283041/148276309-e783c4d1-a9fb-4823-a848-6e9e74708c9f.png)

**Comment by thorrrr** [comment]
i might have to re load a backup

**Comment by jseidl** [comment]
> i might have to re load a backup

That's really weird, integrations would not affect HACS itself AFAICT even if they were broken

**Comment by thorrrr** [comment]
ok got it back do i still need to removes areas ?

**Comment by jseidl** [comment]
If you had removed it before than the 3.x-beta shall have reconstructed it correctly and the update (beta1) wouldn't change it much. 

Did it worked?

**Comment by thorrrr** [comment]
I have rstored from 8 hours ago so everything is as it was nothing removed i now see a HACS upgrad for Magic Rooms

**Comment by thorrrr** [comment]
https://xbackbone.daddycloud.co.uk/Piqa4/SeJOFIYi24.jpg

**Comment by thorrrr** [comment]
What i am saying is i am currently on ver 2 can i directly update now?
Or do i still need to remove each room ?

**Comment by jseidl** [comment]
Update, then before you restart remove all rooms then restart

**Comment by thorrrr** [comment]
it has loaded but not picked up my living room the old one did new ver not seeing it ???

**Comment by thorrrr** [comment]
See [here ](https://xbackbone.daddycloud.co.uk/Piqa4/fuvOsiSe42.jpg)

**Comment by jseidl** [comment]
You need to enable the `Media player groups` feature

**Comment by thorrrr** [comment]
No i mean it is not even picking up the motion sensors in the Living Room

**Comment by jseidl** [comment]
Can you post a screenshot of the attributes of the `binary_sensor.living_room` ? Also double check that the sensors are in the `Living Room` area in Home Assistant

**Comment by thorrrr** [comment]
https://xbackbone.daddycloud.co.uk/Piqa4/XEFECoga54.jpg

**Comment by thorrrr** [comment]
https://xbackbone.daddycloud.co.uk/Piqa4/qEFuVUPo30.jpg

**Comment by jseidl** [comment]
Weird, didn't seems like it created any. Can you post a secreenshot of the integration page, like this 
![image](https://user-images.githubusercontent.com/283041/148285205-a9af3b39-9f66-49b2-9a07-289f5a44ec41.png)

**Comment by thorrrr** [comment]
https://xbackbone.daddycloud.co.uk/Piqa4/SeFiQeqI13.jpg

**Comment by jseidl** [comment]
Do you see "Living Room" on the list? If so, can you click the `>` arrow then entities and post screenshot?

**Comment by thorrrr** [comment]
Nope that’s what i mean it is not in the list

**Comment by jseidl** [comment]
wth... alright time to pull out the big guns

Can you set the log level for `custom_components.magic_areas.binary_sensor` to `debug`? If you don't currently have it defined, the full statement would look like this

```
logger:
  default: warn
  logs:
    custom_components.magic_areas.binary_sensor: debug
```

Then restart & check/post the logs

**Comment by jseidl** [comment]
Hmmm weird it seems to completely ignore the existence of the "Living Room" area.

Let's change a bit:
```
logger:
  default: warn
  logs:
    custom_components.magic_areas: debug
    custom_components.magic_areas.binary_sensor: warn
    custom_components.magic_areas.light: warn
    custom_components.magic_areas.climate: warn
    custom_components.magic_areas.media_player: warn
    custom_components.magic_areas.sensor: warn
    custom_components.magic_areas.switch: warn
    custom_components.magic_areas.cover: warn
    custom_components.magic_areas.config_flow: warn
```

This shall give us the initializer logs while suppressing the other features for now.

**Comment by thorrrr** [comment]
https://0bin.net/paste/vdYuiRLQ#McxTIGm8jr6ThzDCu0koYmoENiJq-s1KvZu/AJYi3/D

**Comment by jseidl** [comment]
It's like the area didn't existed but I recall in a previous screenshot some devices assigned to a Living Room area. Just for peace of mind, can you double check the Areas section on Home Assistant and see if Living Room doesn't have any funny business? Should look something like this

![image](https://user-images.githubusercontent.com/283041/148291343-b02cac66-573e-4bf5-8621-4be74895d4d9.png)

**Comment by jseidl** [comment]
Are there other areas not loading or only Living Room?

**Comment by thorrrr** [comment]
![image](https://user-images.githubusercontent.com/8170673/148292572-003d0983-f837-4990-b105-d050c724ed25.png)

**Comment by thorrrr** [comment]
![image](https://user-images.githubusercontent.com/8170673/148292764-0e87c297-b5a9-4f94-80e2-718e771aee13.png)

**Comment by jseidl** [comment]
So Kitchen and Living Room are missing from my count. That is WEIRD. Trying to think of what's going on there....

**Comment by jseidl** [comment]
Can you edit `custom_components/magic_areas/__init__.py` on line 44 add `_LOGGER.debug(f"Areas from registry: {areas}")` and restart? Want to see what is coming out the area registry

**Comment by thorrrr** [comment]
Like this 

![image](https://user-images.githubusercontent.com/8170673/148295070-4b563f58-8101-44fa-a352-d8191a68edd1.png)

**Comment by jseidl** [comment]
One indent back, like
```
    # Populate MagicAreas
    areas = list(area_registry.async_list_areas())
    _LOGGER.debug(f"Areas from registry: {areas}")

    if DOMAIN not in config.keys():
        _LOGGER.error(f"'magic_areas:' not defined on YAML. Aborting.")
        return
```

**Comment by thorrrr** [comment]
you want logs again?

**Comment by jseidl** [comment]
Yeah, this is the output I get on mine
```
2022-01-05 13:57:36 DEBUG (MainThread) [custom_components.magic_areas] Areas from registry: [AreaEntry(name="Soph's Room", normalized_name="soph'sroom", picture=None, id='933cf153d1c246719e20a44aefbc143a'), AreaEntry(name='Office', normalized_name='office', picture=None, id='e1cafe35d9a04ba89dd3893d1a9251aa'), AreaEntry(name='Living Room', normalized_name='livingroom', picture=None, id='8bf2da2134e646108154af355fbeafa4'), AreaEntry(name='Front Door', normalized_name='frontdoor', picture=None, id='426e35176dd149afac8c7d84a603fdcd'), AreaEntry(name='Backyard', normalized_name='backyard', picture=None, id='cb8e076e8939415f804a02fbb24e5241'), AreaEntry(name='Bathroom', normalized_name='bathroom', picture=None, id='628ef8e06c2d41cdaeacb8f6d00cd618'), AreaEntry(name='Kitchen', normalized_name='kitchen', picture=None, id='e64f5bd02b2846a8b712d88115491999'), AreaEntry(name='Family Room', normalized_name='familyroom', picture=None, id='e2bf4e87fca011ea9ecf17e0cd567b40'), AreaEntry(name='Master Bathroom', normalized_name='masterbathroom', picture=None, id='edfeac4ffca011eab7a2f9e6dd71e231'), AreaEntry(name='Master Bedroom', normalized_name='masterbedroom', picture=None, id='f1217d9ffca011ea9ffc67f8613af79a'), AreaEntry(name='Entrance Hall', normalized_name='entrancehall', picture=None, id='de9da804011011eb9cf6bfe74f84908c'), AreaEntry(name='Garage', normalized_name='garage', picture=None, id='268beedd011111eba155b3c066a930f9'), AreaEntry(name='Dining Room', normalized_name='diningroom', picture=None, id='54f6713b011111eb82b923d51236285c'), AreaEntry(name='Hallway', normalized_name='hallway', picture=None, id='5efc8fa2011e11eb9409272c85dce219')]
```

**Comment by thorrrr** [comment]
were am i looking for this ?

**Comment by jseidl** [comment]
Regular HA logs, you can ctrl+F for "registry", shall show up

**Comment by thorrrr** [comment]
https://0bin.net/paste/yJheAvzQ#gFUsCnY8HckEJFvmXpmFb0hofi3qHAl2zoL5kpJZAzg

**Comment by jseidl** [comment]
Huh... they're the areas you have a picture on it...... that's weird...

**Comment by thorrrr** [comment]
that’s the new areas released a few weeks ago

**Comment by jseidl** [comment]
Yeah I saw but didn't expected to affect Magic Areas, combing through the code to see where might have derailed

**Comment by thorrrr** [comment]
well kitchen has image but that is in list

**Comment by jseidl** [comment]
Yeah both Living Room and Kitchen have an image and both are missing. Looking through the code but I don't have anything referenced by indexes which could be an issue. Trying to figure out what is going on

**Comment by thorrrr** [comment]
well FYI i have removed images and restarted but still not in list

**Comment by thorrrr** [comment]
can i leave it with you drop me a line if you need me to do anything tomorrow

**Comment by jseidl** [comment]
I think I've found it. Not only they have a picture but actually they moved `id` to `normalized_name` and gave a new random ID. That must be it, lemme work on it and I'll ping you here once I have an update

**Comment by thorrrr** [comment]
kewl

**Comment by jseidl** [comment]
Well that's confusing, my areas also have both text ids and random ids and all work, I've also created a new area with a picture and also works... digging a bit more over here

**Comment by jseidl** [comment]
>2022-01-05 14:23:31 DEBUG (MainThread) [custom_components.magic_areas] Areas from registry: [AreaEntry(name="Soph's Room", normalized_name="soph'sroom", picture=None, id='933cf153d1c246719e20a44aefbc143a'), AreaEntry(name='Office', normalized_name='office', picture=None, id='e1cafe35d9a04ba89dd3893d1a9251aa'), AreaEntry(name='Living Room', normalized_name='livingroom', picture=None, id='8bf2da2134e646108154af355fbeafa4'), AreaEntry(name='Front Door', normalized_name='frontdoor', picture=None, id='426e35176dd149afac8c7d84a603fdcd'), AreaEntry(name='Backyard', normalized_name='backyard', picture=None, id='cb8e076e8939415f804a02fbb24e5241'), AreaEntry(name='Bathroom', normalized_name='bathroom', picture=None, id='628ef8e06c2d41cdaeacb8f6d00cd618'), AreaEntry(name='Kitchen', normalized_name='kitchen', picture=None, id='e64f5bd02b2846a8b712d88115491999'), AreaEntry(name='Family Room', normalized_name='familyroom', picture=None, id='e2bf4e87fca011ea9ecf17e0cd567b40'), AreaEntry(name='Master Bathroom', normalized_name='masterbathroom', picture=None, id='edfeac4ffca011eab7a2f9e6dd71e231'), AreaEntry(name='Master Bedroom', normalized_name='masterbedroom', picture=None, id='f1217d9ffca011ea9ffc67f8613af79a'), AreaEntry(name='Entrance Hall', normalized_name='entrancehall', picture=None, id='de9da804011011eb9cf6bfe74f84908c'), AreaEntry(name='Garage', normalized_name='garage', picture=None, id='268beedd011111eba155b3c066a930f9'), AreaEntry(name='Dining Room', normalized_name='diningroom', picture=None, id='54f6713b011111eb82b923d51236285c'), AreaEntry(name='Hallway', normalized_name='hallway', picture=None, id='5efc8fa2011e11eb9409272c85dce219'), AreaEntry(name='3D Printer Cabinet', normalized_name='3dprintercabinet', picture='/api/image/serve/daadf708f7b2e334dc2c8b783f3f3006/512x512', id='3d_printer_cabinet')]

then

>2022-01-05 14:23:31 DEBUG (MainThread) [custom_components.magic_areas] AREA 3d_printer_cabinet 3D Printer Cabinet: {'type': 'interior', 'update_interval': 60, 'features': {}, 'clear_timeout': 60, 'exclude_entities': [], 'presence_sensor_device_class': ['motion', 'occupancy', 'presence'], 'presence_device_platforms': ['media_player', 'binary_sensor'], 'on_states': ['on', 'open'], 'include_entities': [], 'icon': 'mdi:texture-box', 'secondary_states': {'sleep_entity': '', 'accent_state': 'on', 'sleep_state': 'on', 'dark_state': 'on', 'sleep_timeout': 60, 'extended_time': 120, 'extended_timeout': 300, 'accent_entity': '', 'dark_entity': ''}, 'name': '3D Printer Cabinet', 'id': '3d_printer_cabinet'}

**Comment by thorrrr** [comment]
Sorry what are you saying to me

**Comment by jseidl** [comment]
Still on `__init__.py`, around line 88, add this logging before the `async_create_task` line. Should be something like this

` _LOGGER.debug(f"Creating config flow task for area {area.name} ({area.id}): {config_entry}")`

```
        _LOGGER.debug(f"Creating config flow task for area {area.name} ({area.id}): {config_entry}")
        hass.async_create_task(
            hass.config_entries.flow.async_init(
                DOMAIN, context={CONF_SOURCE: source}, data=config_entry
            )
        )
```

Then do the same, restart and post me the logs from `registry` down

> Sorry what are you saying to me

That I still can't reproduce the issue and still looking into it!

**Comment by jseidl** [comment]
I've created a community discord server just now, might be able to better help you than the ticket https://discord.gg/8vxJpJ2vP4

**Comment by thorrrr** [comment]
In bed now will do it tomorrow. Also I have joined discord invite

**Comment by thorrrr** [comment]
Dropped log in Dicord
