### ISSUE TITLE
Warning on device_state_attributes

### ISSUE THREAD

**Issue by felix63** [jseidl/hass-magic_areas#164]
You are probably already aware but I get a lot of these since 2012.12:
`Entity sensor.area_current_a_global (<class 'custom_components.magic_areas.sensor.AreaSensorGroupSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.area_pressure_hpa_global (<class 'custom_components.magic_areas.sensor.AreaSensorGroupSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.area_signal_strength_dbm_global (<class 'custom_components.magic_areas.sensor.AreaSensorGroupSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity binary_sensor.area_interior (<class 'custom_components.magic_areas.binary_sensor.AreaPresenceBinarySensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity binary_sensor.area_exterior (<class 'custom_components.magic_areas.binary_sensor.AreaPresenceBinarySensor'>) implements device_state_attributes. Please report it to the custom component author.`

**Comment by jseidl** [comment]
Thanks @felix63 this is fixed on 3.0.0-beta, thanks for reporting!
