### ISSUE TITLE
Log Details (WARNING)

### ISSUE THREAD

**Issue by cloudbr34k84** [jseidl/hass-magic_areas#175]
Hi im getting this warning in my Logs.

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:574
First occurred: 11:15:49 (47 occurrences)
Last logged: 11:15:54

Entity binary_sensor.area_driveway (<class 'custom_components.magic_areas.binary_sensor.AreaPresenceBinarySensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity switch.area_presence_hold_driveway (<class 'custom_components.magic_areas.switch.AreaPresenceHoldSwitch'>) implements device_state_attributes. Please report it to the custom component author.
Entity binary_sensor.area_global (<class 'custom_components.magic_areas.binary_sensor.AreaPresenceBinarySensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity binary_sensor.area_interior (<class 'custom_components.magic_areas.binary_sensor.AreaPresenceBinarySensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity binary_sensor.area_exterior (<class 'custom_components.magic_areas.binary_sensor.AreaPresenceBinarySensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by jseidl** [comment]
Hi! This is being fixed on the next release, thanks!
