### ISSUE TITLE
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by Zipties** [jseidl/hass-magic_areas#176]
When trying to configure a room named "Upstairs" I get the following error. All other rooms work fine. I have tried deleting the Upstairs integration and letting it rebuild it, and reinstalling the entire component, but the issue with this room is still there. 

![CleanShot 2022-02-07 at 10 18 53@2x](https://user-images.githubusercontent.com/11506166/152828060-cb8a7825-3d44-47da-88be-50c35ffa28c9.jpg)
[home-assistant.log](https://github.com/jseidl/hass-magic_areas/files/8016896/home-assistant.log)

**Comment by jseidl** [comment]
Hi! Which version are you on? I checked the log but couldn't find anything screaming at me there.

**Comment by jseidl** [comment]
Hi is this still an issue?

**Comment by jseidl** [comment]
This is because you have a group in an area and Home Assistant replaces the `entity_id` attribute with a list with the members' entity ids. 

This is fixed in the `develop` branch and shall be going out on the release tomorrow.

**Comment by jseidl** [comment]
Fixed on 3.0. If the issue persists, please reopen!
