### ISSUE TITLE
Support adding back after disabling an area

### ISSUE THREAD

**Issue by rschoultz** [jseidl/hass-magic_areas#177]
An area that has been disabled does not seem to be able to be added back into the integration. Is there another way than re-installing and reconfiguring all the areas again?

**Comment by jseidl** [comment]
You mean you can't add back after re-enabling? Have you tried removing the entry on Magic Areas and restarting?

**Comment by jseidl** [comment]
Hi is this still an issue?

**Comment by jseidl** [comment]
Closing due lack of communication. Please reopen if still persists.

**Comment by rschoultz** [comment]
Jan, found out with the arrow symbol it was possible. Apologies for having you waste time on this. I would have closed if I had noticed your follow-up.
