### ISSUE TITLE
control_ flags should default to false

### ISSUE THREAD

**Issue by ontolo-zz** [jseidl/hass-magic_areas#18]
Following the principle of 'least surprise' the control flags should be false by default unless set true globally or per area by the user adding these flags in config.

The current approach can cause user surprise by turning off media players, for example, in a newly created area. Keep in mind that the new area might be created some months from now.

**Expected**
A user create a new area, the sensors in it are magically aggregated and available for use in automations.
The user is aware magic_areas can control some devices, and can set the relevant control_ flag true to avoid having to script this.

**Actual**
A user create a new area, the sensors in it are magically aggregated and available for use in automations.
The user is unaware that magic_areas will turn devices off in this new area, and does not desire this behaviour.
Possibly this takes the user a very long time to resolve if they don't know the cause.

Aggregation should be separate from control here. At a minimum it should be possible to _globally_ turn off control and only use the aggregation magic. Defaulting false would be preferable.

**Comment by jseidl** [comment]
That's a valid point. Will schedule this change for the next major revision as is a breaking change

**Comment by ontolo-zz** [comment]
Great stuff!

Depending on how long you expect until the next major release it might be worth adding optional global control_ switches before then. This would allow users to turn _off_ the control_ globally in their HA (including for areas which yet don't exist) and would not be a breaking change for the existing config.

**Comment by jseidl** [comment]
Adding a note to future me, this will be part of a big change where global settings will be introduced for many parameters allowing override per area.

**Comment by jseidl** [comment]
This is coming as part of a major rework. First stage will be moving all features apart from the main presence `binary_sensor` to *not enabled* by default. See #72 for more information.

Second stage will have global options but I'm still working out on that one.
