### ISSUE TITLE
Wiki - Presence hold - timeout 

### ISSUE THREAD

**Issue by maxfield-allison** [jseidl/hass-magic_areas#209]
Timeout description is missing the unit of time used for the timeout, Seconds. Suggest changing to minutes, hours, or a time field.

**Comment by jseidl** [comment]
Thanks will add the time unit. Changing to minutes would make sense but break existing users. (not dealbreaker, but to consider)

**Comment by jseidl** [comment]
Wiki fixed, UI will also hint the time unit (coming up on next release)
