### ISSUE TITLE
Log warning: Deprecated 'async_get_registry'  after upgrade to 2022.6.3

### ISSUE THREAD

**Issue by ShadowFistOkami** [jseidl/hass-magic_areas#213]
Hi, just wanted to give you a heads up regarding the following error in HA logs immediately after upgrade from 2022.5.3 to 2022.6.3

`Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 11:28:23 (6 occurrences)
Last logged: 11:28:44

Detected integration that uses deprecated `async_get_registry` to access area registry, use async_get instead. Please report issue to the custom component author for magic_areas using this method at custom_components/magic_areas/__init__.py, line 41: area_registry = await hass.helpers.area_registry.async_get_registry()
Detected integration that uses deprecated `async_get_registry` to access area registry, use async_get instead. Please report issue to the custom component author for magic_areas using this method at custom_components/magic_areas/__init__.py, line 127: area_registry = await hass.helpers.area_registry.async_get_registry()

Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom component author for magic_areas using this method at custom_components/magic_areas/base.py, line 352: entity_registry = await self.hass.helpers.entity_registry.async_get_registry()
Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for magic_areas using this method at custom_components/magic_areas/base.py, line 334: await self.hass.helpers.device_registry.async_get_registry()`

**Comment by jseidl** [comment]
Ty! Will fix in the next release since it seems to be non-breaking for now

**Comment by jseidl** [comment]
Fixed on 3.0.
