### ISSUE TITLE
Support either brightness changes or scene changes on day vs night

### ISSUE THREAD

**Issue by bmcclure** [jseidl/hass-magic_areas#214]
Currently you can select different lights for day vs night, but what if you want to use the same lights but have them turn on to a set brightness depending on whether it's day or night?

I'd light to have the lights work like normal during the day, but in the middle of the night I'd like them to turn on as dimly as possible.

**Comment by jseidl** [comment]
You can do that using [Adaptive Lighting](https://github.com/basnijholt/adaptive-lighting).

**Comment by bmcclure** [comment]
It seems like a sledgehammer when I'm trying to hammer in a tiny tack (turning lights on at the brightness I set), but it looks sufficiently impressive so I'll give it a try. Thanks!

**Comment by bmcclure** [comment]
I'm coming around to the idea more and more. I don't need most of the functionality that Adaptive Lighting offers, but there are a couple of nice things that make me think it's worth it to manage brightness independently of my on/off automations. Thanks again for the suggestion.
