### ISSUE TITLE
Areas are showing occupancy after HA update

### ISSUE THREAD

**Issue by grinco** [jseidl/hass-magic_areas#218]
After today's update to 2022.6.6 most areas are stuck at showing as occupied. Not sure what causes some to show as occupied, while others - not.

**Comment by grinco** [comment]
nevermind, downgrading to 2022.6.5 worked for two days and it broke again today. after updating to 2022.6.6, installation of the 3.0.0 beta, and downgrading back to 2.0.05 it started working again. is there a way to see what triggers the area to be active? it used to be an attribute - which is missing now.

**Comment by jseidl** [comment]
Hi @grinco, 3.0 should be going into release tomorrow night (PDT). If you wanna test meanwhile, the code on the `develop` branch is the latest working one.

The `active_sensors` attribute will show which sensors are triggering an area.

**Comment by jseidl** [comment]
Should be fixed on the latest release, please check!

**Comment by jseidl** [comment]
Fixed on 3.0. If the issue persists, please reopen!
