### ISSUE TITLE
Bug: turning off sleep state turns on sleep lights before turning off overhead lights

### ISSUE THREAD

**Issue by mouth4war** [jseidl/hass-magic_areas#238]
**Describe the bug**
turning off sleep state turns on sleep lights before turning off overhead lights. Overhead lights should be turned off first.

**To Reproduce**

**Expected behavior**
Overhead lights should be turned off first. Then sleep lights turned on.

**Comment by jseidl** [comment]
Hi, turning `OFF` sleep states turns sleep lights `ON`? Should be turning it `OFF`. Is there a mistype or is it indeed turning off when it should turn on?

If the sleep lights are turning on before the others turn off, then that's expected. The whole process is asynchronous so there is no way to guarantee order of execution on these.
