### ISSUE TITLE
Feature Request: Climate temperature / hvac_mode

### ISSUE THREAD

**Issue by sti0** [jseidl/hass-magic_areas#24]
Could you please add the ability to set a temperature and maybe the hvac mode (e.g. delivered by a sensor)? 

Some climate implementations will turn on boost mode when the service `climate.turn_on` was called (e.g. https://www.zigbee2mqtt.io/devices/SPZB0001.html , there was a long discussion about this implementation and that's the final result). Normal heating mode is used when turing on the "auto" hvac mode. In such a case the service `climate.set_temperature` should be used instead as we can deliver both `temperature` and `hvac_mode`.

**Comment by jseidl** [comment]
Meanwhile, you could set an automation to configure these settings when the climate changes state to on.

**Comment by sti0** [comment]
That's true. But this means that the climate turns on with a heat state which means it turns on boost at 30°C. Afterwards an automation must change the temperature to a lower level. I think I use my time-based schedules instead until this feature comes true.

Maybe it would be better to implement the opinion to set the climate to an eco mode / temperature instead of turning it off completely. At winter months I ran my climate on a lower level to prevent frost / cooling out the room to much.

**Comment by jseidl** [comment]
#126 is moving from `off/on` to `set_hvac_mode`. Let's see how that goes!

**Comment by jseidl** [comment]
This is confirmed working on `3.0.0-beta`
