### ISSUE TITLE
Removing (all) lights from a certain group doesn't work 

### ISSUE THREAD

**Issue by tbrasser** [jseidl/hass-magic_areas#248]
**Describe the bug**
Cannot remove lights from groups

**To Reproduce**
1. Go to 'config flow of any configured magic area with light groups'
2. Remove any light from a group
3. Save 
4. Group with removed light in it still exists. 

**Expected behavior**
Removing a light should remove that config selector as well, removing the last light should delete the group too (maybe it does but I can't get the lights removed first) 

**Screenshots**
1. Nachtkastje is in the task group 
!["nachtkastje" is in tasks group](https://user-images.githubusercontent.com/2816560/180763888-b26d18c7-6419-4ab7-b6f7-e6d456587b6c.jpg)

2. Nachtkastje is removed but there's still 2 entity selectors available
![When I click "x" there's still 2 entity selectors visible instead of the selected 1](https://user-images.githubusercontent.com/2816560/180764144-c36f140e-78c0-4ec6-9ef2-18ddde99e1ae.jpg)

3. After saving it's still there
![after saving, it's still there](https://user-images.githubusercontent.com/2816560/180764263-18b63b1a-889f-4699-be60-554a91131689.jpg)

**Comment by jseidl** [comment]
Thanks for reporting, will look into it

**Comment by jseidl** [comment]
Hi, I've just tried to reproduce this bug but had a different experience. The selector did disappear and when I saved, it did removed the entries.

Are you on the latest release (3.0.1)? Is this a fresh install or are you coming from the beta or 2.x release?

**Comment by jseidl** [comment]
Closing due inactivity, if still persists, please reopen.
