### ISSUE TITLE
Bug: Dead lock when Magic area is assigned to its Area

### ISSUE THREAD

**Issue by juacas** [jseidl/hass-magic_areas#255]
**Describe the bug**
When a"magic Area Entity" is assigned to its Area and it is activated ("on"), it never goes off because it detects itself as a valid entity for calculating the new state.

**To Reproduce**
1. Assign a Magic Area Entity to its represented HA Area
2. Make the MAgic Areato enter the "on" state.
3. See that neves goes "off". Logs shows that the reason is its own previous state.

**Expected behavior**
A Magic Area should ignore itself when checking the states.

**Additional context**
Adding a Magic Area  to the HA Area allow to be browsed easier. I fact, I suggest that a Magic Area Entity registers itself in the actual Area by default.

Thanks for this component.

**Comment by jseidl** [comment]
That's true, I do need to add some logic to prevent this from happening. Thanks for opening the ticket!

**Comment by jseidl** [comment]
This is fixed by #300
