### ISSUE TITLE
Can't use Sun Integration as dark state?

### ISSUE THREAD

**Issue by J0n4t4n** [jseidl/hass-magic_areas#256]
Hi,
I have just started to use this Integration to hopefully replace my DIY light setup that I previously used.
Sadly I can't figure out one thing that is a major blocker for me using the Integration.

I use the Sun Integration and the resulting sun.sun state as my "dark state" trigger in my old setup and want to continue using it.
But it seems like I can't select sun.sun in the "Entity used to track area dark state" field.
Is that a bug or am I missing something?

I'm using version 3.0.1 currently.

Thanks!

**Comment by jseidl** [comment]
Whoops. Forgot to add the `SUN_DOMAIN` to [that list](https://github.com/jseidl/hass-magic_areas/blob/master/custom_components/magic_areas/const.py#L563-L574). 

Should be an easy fix, but I'm short on time due recently becoming a parent. Will work on it as soon as time permits!

**Comment by klatka** [comment]
> Whoops. Forgot to add the `SUN_DOMAIN` to [that list](https://github.com/jseidl/hass-magic_areas/blob/master/custom_components/magic_areas/const.py#L563-L574).
> 
> Should be an easy fix, but I'm short on time due recently becoming a parent. Will work on it as soon as time permits!

Hey, I added the `SUN_DOMAIN` to the list you have mentioned
