### ISSUE TITLE
Bug: Settings being overwritten on update

### ISSUE THREAD

**Issue by sjthespian** [jseidl/hass-magic_areas#259]
**Describe the bug**
I have several lights that I want Magic Areas to turn off, but not turn on. In order to do this, I remove all values from "States which overhead lights are turned on". However, every time I edit the settings it adds "occupied" to this setting, and if I don't catch it that means that lights will once again turn on due to motion. This can be a problem with things like the bedroom ceiling light that I don't want coming on if someone is sleeping and the house isn't in "sleep" mode.

A related problem... once you remove a value from that field by clicking the "X", it doesn't appear in the available values until you either type part of the name or remove another value.

**To Reproduce**
1. Edit the settings for an area
2. Remove all values from "States which overhead lights are turned on" in Light Groups
3. Save the settings
4. Edit the settings again and see that "occupied" has been added to the above setting.

**Expected behavior**
Once the values are cleared from that setting I would expect them to stay gone.

**Desktop (please complete the following information):**
 - OS: MacOS 12.6
 - Browser Chrome
 - Version 105.0.5195.125

**Comment by jseidl** [comment]
There's a part of the code that checks if you have a  configured value there, if not it gives you the default value. It's not straightforward to fix because I need a way to know if "is this unset or blank by choice", will work on it

**Comment by klatka** [comment]
You can see this behavior also at number boxes. If you set 0 and reopen config, MA sets the default value.

**Comment by klatka** [comment]
> There's a part of the code that checks if you have a configured value there, if not it gives you the default value. It's not straightforward to fix because I need a way to know if "is this unset or blank by choice", will work on it

It's already working for states of different light groups.

**Comment by jseidl** [comment]
This has been fixed, coming up on next update! Closing this one to better track the ones I still have to work on.
