### ISSUE TITLE
Integration is using deprecated `DEVICE_CLASS_*` constants

### ISSUE THREAD

**Issue by frenck** [jseidl/hass-magic_areas#266]
**Describe the bug**

This custom integration uses deprecated `DEVICE_CLASS_*` constants in its codebase.

The `DEVICE_CLASS_*` constants have been deprecated and replaced in Home Assistant Core 2021.12 (over a year ago). I would highly suggest updating/migrating this integration to the new enums.

For example, for the device classes supported by the `sensor` platform, there is now a `SensorDeviceClass` enum. So if a sensor previously used the `DEVICE_CLASS_ENERGY` constant, it should now use `SensorDeviceClass.ENERGY`. Other platforms (like `binary_sensor`, and `number`) provide similar enumerations for their supported device classes.

The migration thus only consists of replacing constants with an enumeration member and is, therefore, very low impact and should be fairly straightforward.

If I can help resolve any questions regarding this change or migration, feel free to ask or respond to this issue. I'm happy to help!

Kindest regards,

../Frenck

**To Reproduce**
n/a

**Expected behavior**
n/a

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Any
 - Browser [e.g. chrome, safari] Any
 - Version [e.g. 22] Any

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Any
 - OS: [e.g. iOS8.1] Any
 - Browser [e.g. stock browser, safari] Any
 - Version [e.g. 22] Any

**Additional context**

n/a

**Comment by jseidl** [comment]
Awesome, thanks for the report, will work on those today. 

Is there a best place where I can keep track of those changes for devs?

**Comment by frenck** [comment]
> Is there a best place where I can keep track of those changes for devs?

The developer blog @ developers.home-assistant.io.
The major changes are also listed in the breaking changes section of each major Home Assistant release in the release notes.

**Comment by jseidl** [comment]
Thanks, got a PR fixing those, appreciate the report! Lemme know if you spot anything else. Will keep an eye on the blog!

**Comment by frenck** [comment]
Awesome! Thanks for resolving this one @jseidl 👍 

../Frenck
