### ISSUE TITLE
Bug: drop downs in configuration for light groups don’t work

### ISSUE THREAD

**Issue by mouth4war** [jseidl/hass-magic_areas#268]
**Describe the bug**
Cannot configure light groups because drop downs for options aren’t showing any entries. Cannot choose states or 

**To Reproduce**
1. Go to configuration for a magic area in the settings for HASS. 
2. Click through till you reach light groups configuration
3. Scroll down to the two drop downs for state and when. 
4. Drop down is empty

**Expected behavior**
Earlier, drop downs worked fine. You would see the available options and be able to select.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jseidl** [comment]
Can you confirm that you area has lights on it?

**Comment by jseidl** [comment]
Closing due inactivity, please reopen if you still have this issue.
