### ISSUE TITLE
Documentation: sleep_entities leads to false configuration

### ISSUE THREAD

**Issue by sti0** [jseidl/hass-magic_areas#27]
In the documentation there is an error on the `autolights `description. The mentioned `sleep_entities` option leads to a false configuration. According to your blog post it has to be `sleep_lights`.

![image](https://user-images.githubusercontent.com/18382402/97023645-18a88480-1556-11eb-84d7-e026bb477924.png)

**Comment by jseidl** [comment]
You mean the name being both in singular and plural is confusing? Would `sleep_lights` be a better parameter name?

**Comment by sti0** [comment]
No, in the documentation you named it `sleep_entites` which leads to a configuration error. For a working configuration it must be `sleep_lights`.

**Comment by jseidl** [comment]
Feature added by @sti0 on the `develop` branch.

Scheduled for `1.1.0` release.
