### ISSUE TITLE
Bug: connectivity sensor should return off if at least one sensor is not connected

### ISSUE THREAD

**Issue by klatka** [jseidl/hass-magic_areas#271]
**Describe the bug**
Not sure if it's a bug but the connectivity sensor should return off if at least one sensor is not connected.
Currently, the sensor is always on until all sensors are off.

**Expected behavior**
If attributes.active_sensors count != attributes.sensors then return off
 
Magic Areas version 3.0.1

**Comment by jseidl** [comment]
Current all binary sensor groups are using this `all = False`, but good point, will take a look onto that

**Comment by jseidl** [comment]
This should be an easy fix similar to what I did for regular sensor aggregates that should be sum instead of avg. 

Can you take a look at the binary sensor device classes and compile a list of possible candidates for that same behavior (only if all are on, be on)?

**Comment by klatka** [comment]
The connectivity sensor is currently the only one.

**Comment by klatka** [comment]
Looks like only binary_sensor is considered.
This should also be included:

```
{{ states.sensor
  | selectattr('attributes.device_class', 'defined')
  | selectattr('attributes.device_class', 'eq', 'connectivity')
  | selectattr('attributes.state_class', 'defined')
  | selectattr('attributes.state_class', 'eq', 'measurement')
  | map(attribute='entity_id')
  | list }}
```

**Comment by jseidl** [comment]
@klatka binary_sensors and sensors are not aggregated together, there's no inference of connectivity due presence of value.

This could be a good addition to the Area Health Sensors tho
