### ISSUE TITLE
Rooms not loading

### ISSUE THREAD

**Issue by Patrick1610** [jseidl/hass-magic_areas#278]
Hi, 

I still havn't had the time to update to Magic Areas 3, so i'm still running 2.0.5.
After updating to HA 2023.1, none of my areas/rooms are loading. 

Any idea how this is possible and how to fix it? 
Is updating to 3.0 needed as of now? 

Regards, 
Patrick

**Comment by klatka** [comment]
I would highly recommend using version 3 upwards

**Comment by Patrick1610** [comment]
Thanks, I've updated and that seemed to work!
