### ISSUE TITLE
Bug: Presence hold timeout not long enough

### ISSUE THREAD

**Issue by bmcclure** [jseidl/hass-magic_areas#287]
**Describe the bug**
The presence hold timeout feature is useful in case someone forgets to turn off Presence Hold once they no longer need it. However, the highest number that the configuration screen will let me enter is 9999 which is only 2.778 hrs. I was trying to enter 28800 which I believe is 8 hours, but the input turns red and prevents me from continuing after I enter a 5th digit.

**To Reproduce**
1. Configure an area with a presence hold switch
2. Try and enter a presence hold timeout larger than 9999 seconds

**Expected behavior**
It should allow for much larger numbers, or perhaps it should use minutes instead of seconds.

**Additional context**
It seems to me people might want to have a long Presence Hold period, but still use the timeout feature. My desire currently is for 8 hours, but I could easily see someone wanting a presence hold timeout of 24 hours, or maybe even longer.

**Comment by bmcclure** [comment]
In re-evaluating this request, perhaps it should be classified as an enhancement vs a bug, because I'm not sure what the original intention was as far as the upper bounds of the timeout.

**Comment by jseidl** [comment]
This is probably something that would be fixed by changing the timeouts from seconds to minutes, which would make more sense in that directive.

The bad thing is that is not backwards compatible so people would have to update, which is not a dealbreaker but it makes it so it has to go in a major release.

I'm up for this and it's being tracked here https://github.com/jseidl/hass-magic_areas/discussions/254, make sure you upvote!

**Comment by bmcclure** [comment]
Oh totally, changing from seconds to minutes would be great! I upvoted that issue, looking forward to that hopefully making it in!

Could async_migrate_entry be used when updating to the newer version to migrate existing seconds values to minutes automatically?

**Comment by jseidl** [comment]
> Could async_migrate_entry be used when updating to the newer version to migrate existing seconds values to minutes automatically?

Possibly! Although I never messed with it, have to take a look at it

**Comment by jseidl** [comment]
This is being tracked on https://github.com/jseidl/hass-magic_areas/discussions/254, please upvote. I am strongly inclined to doing this one but it's a breaking change so I'm waiting until I get the new naming convention out (still 1 or 2 releases out) so I make all the breaking changes at once.
