### ISSUE TITLE
Feature Request: Sleep clear_timeout

### ISSUE THREAD

**Issue by sti0** [jseidl/hass-magic_areas#29]
A dynamic clear_timeout by template / sensor or a second `clear_timeout` attribute for sleep configuration would be nice.

Real world example:
  Presence in the area is measured by one motion sensor. During the day the `clear_timeout` is set to 360 seconds, because there is not that much movement in the area but the light shouldn't turn on and off the whole time. If there is no movement after 5 minutes, lights turned off. But at night, my two crazy cats are walking along and trigger the sleep lights. The lights stay on for 5 minutes...thats a little waste of energy. In that case it would be nice to clear the area after ...lets say... 30 seconds.

**Comment by jseidl** [comment]
Both ideas are good. I believe `sleep_clear_timeout` would bring the most immediate benefit. Thanks!

**Comment by jseidl** [comment]
Feature added by @sti0 on `develop` branch. 

Scheduled for `1.1.0` release
