### ISSUE TITLE
Bug: Area presence binary sensor including binary sensors without device classes

### ISSUE THREAD

**Issue by chen-ye** [jseidl/hass-magic_areas#295]
**Describe the bug**
Area presence binary sensors include binary sensors without device classes in their calculation.

**To Reproduce**
1. Create a template binary sensor in an area. Give it no device class.
2. Reload magic areas. Open the details modal for the area binary sensor for the area, and open the attributes pane. Observe that the template binary sensor added is included in the "Presence sensor" attribute

**Expected behavior**
Expect binary sensors not to be included unless they have a device class included in the area config.

**Additional context**
Issue seems to be in [this conditional](https://github.com/jseidl/hass-magic_areas/blob/master/custom_components/magic_areas/binary_sensor.py#L190).

If `ATTR_DEVICE_CLASS in entity.keys()` is False, then the conditional evaluates to False, and the sensor is appended to `AreaPresenceBinarySensor`.

**Comment by jseidl** [comment]
Thanks for reporting. I need to investigate. Looking at the code you've mentioned, I'd assume the following would prevent it:

> entity[ATTR_DEVICE_CLASS] not in self.area.config.get(CONF_PRESENCE_SENSOR_DEVICE_CLASS)

I will try to reproduce and see what's going on. Thanks!
