### ISSUE TITLE
2024.2 Magic Area did not start

### ISSUE THREAD

**Issue by fisch55** [jseidl/hass-magic_areas#308]
2024.2 Magic Area did not start 

Logger: homeassistant.setup
Source: setup.py:333
First occurred: 20:56:19 (1 occurrences)
Last logged: 20:56:19

Error during setup of component magic_areas
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 333, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/magic_areas/__init__.py", line 67, in async_setup
    AreaEntry(
TypeError: AreaEntry.__init__() missing 2 required keyword-only arguments: 'icon' and 'picture'

**Comment by geckom** [comment]
As a temporary solution (until the owner can update it). Simple add:

```
                picture=None,
                icon=None
```

To line 72 of __init__.py after "id=meta_area.lower(),"

That is enough to get it started again.

**Comment by pschmitt** [comment]
You could make it easy on them and open a PR ;)

**Comment by grinco** [comment]
There: https://github.com/jseidl/hass-magic_areas/pull/309

**Comment by jseidl** [comment]
Thanks folks! Please use the code in the `main` branch until I can do a new release. Please be  aware that there are features under test there. Otherwise just patch manually your own local copy.

**Comment by andyinno** [comment]
> Thanks folks! Please use the code in the `main` branch until I can do a new release. Please be aware that there are features under test there. Otherwise just patch manually your own local copy.

Features includes something related to climate? From the update my hvac starts below the triggered temperature that I setup. And... It's winter here.

**Comment by jseidl** [comment]
> > Thanks folks! Please use the code in the `main` branch until I can do a new release. Please be aware that there are features under test there. Otherwise just patch manually your own local copy.
> 
> Features includes something related to climate? From the update my hvac starts below the triggered temperature that I setup. And... It's winter here.

It shouldn't! All climate control does is turning on or off when the area is occupied or clear. One thing that might happen is if you assign your central heating to an area that has climate groups then it will turn it off when the area is clear
