### ISSUE TITLE
Bug: 2024.2 error after update.  

### ISSUE THREAD

**Issue by hyperfive** [jseidl/hass-magic_areas#316]
After the latest home assistant installation magic areas will no longer load.  

Here is the error in the logs. 

![IMG_2500](https://github.com/jseidl/hass-magic_areas/assets/46284239/2389c170-00fe-41e7-b33f-fca9788f77c2)

**Comment by jseidl** [comment]
Hi, this is already fixed in the main branch and waiting the beta of the next version to end so I can release it.

You can either get the beta from the main branch and join the test or manually patch it until then. See https://github.com/jseidl/hass-magic_areas/issues/308

**Comment by jseidl** [comment]
Reopening this until 3.1.0 comes out so others can have visibility on this.

**Comment by jseidl** [comment]
Release 3.1.0 is out, please update and this shall be resolved.
