### ISSUE TITLE
Bug: Nothing happens after installation. This integration is automatically configured on load. You don't need to manually add the integration on this UI. Your Magic Areas should be already on the integrations page. Use Home Assistant's built-in areas to create new ones and manage entities.

### ISSUE THREAD

**Issue by makp0** [jseidl/hass-magic_areas#317]
**Describe the bug**
After the first installation no areas are configured and adding integration shows:
"This integration is automatically configured on load. You don't need to manually add the integration on this UI. Your Magic Areas should be already on the integrations page. Use Home Assistant's built-in areas to create new ones and manage entities."

**To Reproduce**
1. Make a clean install from HACS
2. Restart HA
3. Add MA integration
4. See the message

**Expected behavior**
At least something should be configured.

**Screenshots**

![CleanShot 2024-02-13 at 10 15 18](https://github.com/jseidl/hass-magic_areas/assets/22623598/854b621a-51b5-427d-a979-d4aad8869845)
![CleanShot 2024-02-13 at 10 14 51](https://github.com/jseidl/hass-magic_areas/assets/22623598/7075ed44-61da-4a6d-884f-e2b164c26970)
![CleanShot 2024-02-13 at 10 14 39](https://github.com/jseidl/hass-magic_areas/assets/22623598/bf45a024-21c8-419b-904f-3899c6e2de31)
![CleanShot 2024-02-13 at 10 14 36](https://github.com/jseidl/hass-magic_areas/assets/22623598/f221b3a8-04a3-415a-80da-94872e0a9bc3)

**Desktop:**
 - OS: MacOS
 - Browser Arc
 - Version 1.29.0 (46113)
 - Chromium Engine Version 121.0.6167.160
 
 MA v3.0.2

**Comment by jseidl** [comment]
Hi! You're probably missing the `magic_areas:` on your configuration.yaml since you're using 3.0.2. I've overwritten the wiki with instructions for the 3.1.0 version currently in beta that has a slight different install instruction. 

You can check the older version for the installation instructions for 3.0.2 here https://github.com/jseidl/hass-magic_areas/wiki/Installation/625d2876a814a16f6b63a444d9b2b61819c1255e

**Comment by rsperry79** [comment]
Issue was solved by issue #316  fix.

**Comment by jseidl** [comment]
Release 3.1.0 is out, please update and this shall be resolved.
