### ISSUE TITLE
Timer Reset (Area Presence Hold / configurable Entity)

### ISSUE THREAD

**Issue by hirsts** [jseidl/hass-magic_areas#371]
### Discussed in https://github.com/jseidl/hass-magic_areas/discussions/367

<div type='discussions-op-text'>

<sup>Originally posted by **hirsts** June 14, 2024</sup>
I've been using MA for years and LOVE it. It makes HA useful ;-)

One feature that  I would find useful is a way reset timers / timeouts. 

My approach is to have Shelly devices publish the switch state on a seperate MQTT topic and I use this to turn on and off the MA Area Presence Hold Switch for the given area. For example, if when I go into the garage and I know I will be there for an extended period, I hit the power switch which overrides everything and turns on the lights but also turns on the Area Present Hold Switch so MA doesn't turn off the lights if i've been still for too long. Trust me, if you are of out sensor range, half way up a ladder with a heavy box and the lights go out, it can be a bit sketchy. 

The issue I have is that when I leave the room and turn off the light switch, the lights go out but the 10 minute extended timer is still running and so if you reenter the room within the 10 minutes, the lights don't get auto turned back on. 

Ideally what would happen is that when the Area Hold Switch is turned off then any running timers / timeouts should be cancelled. It could be a configurable option and or you might be able to select a different entity that might reset timers.

Happy for thoughts and to discuss.</div>

**Comment by jseidl** [comment]
Hi @hirsts, I saw the post on feature requests, I'll circle back to it when I have some time to go over features. Going to close this one as the issues areas are for bugs only.
