### ISSUE TITLE
Reconfiguring areas needed again

### ISSUE THREAD

**Issue by Patrick1610** [jseidl/hass-magic_areas#372]
Hi @jseidl, 

I have reconfigured most of my areas after the update to 4.x. This wasn't a big deal, but now I am facing the issue that there are areas that are giving the same error as before when opening the config, and the areas stay 'Detected' for a very long time or always. Some of these areas are completely new, or re-added areas. I think the problem is with areas that contain entities that are deleted/unavailable. I have reconfigured some sensors in my backyard and the areas that are part of the backyard are giving me problems. 

I hope this helps with solving the underlying problem. 
I guess for now the solution is to re-add those areas once more, am I correct? 

Regards, Patrick

Hi! Yes sorry about the misunderstanding. Every major release (when the first digit of the version goes up) is potentially breaking. 

I've mentioned on the end of the release notes:
> If anything looks broken, try first deleting and re-creating the Magic Area. If it is still broken, cut me an [issue](https://github.com/jseidl/hass-magic_areas/issues) or come chat on Discord!

Although I've tested a lot during the beta, there are a few odd cases where you might have to delete and re-create some entries. The logs aren't helping much so I wasn't able to pin down what it is but since the config schema changed it might be that.

_Originally posted by @jseidl in https://github.com/jseidl/hass-magic_areas/discussions/360#discussioncomment-9697960_

**Comment by jseidl** [comment]
Hi @Patrick1610 are you still having issue after re-creating the areas?

**Comment by Patrick1610** [comment]
I have now deleted and re-added an area, removed a sensor from Zigbee, restarted HA and added the sensor again. Restarted once more. The area config still works as it should. 

So after the update some areas where broken and some weren't. I deleted and re-added the broken once's. Could it be that the areas that were fine at first are now broken? Because I have very methodically checked all the areas, until every area worked 🤔

**Comment by jseidl** [comment]
Do you still have areas broken after readding them?

**Comment by thoppa** [comment]
I have one area that after deleting shows no devices or entities.

**Comment by jseidl** [comment]
Can you describe your problem in detail? Are you still having on the latest release? Please include logs as well.

**Comment by jseidl** [comment]
Ok release 4.1.0 is out, update and let me know. If you still experience issues please reopen this issue
