### ISSUE TITLE
Ability to control light values in sleep state

### ISSUE THREAD

**Issue by Backslashh** [jseidl/hass-magic_areas#4]
Let me first start by saying that I freaking love this integration. It's exactly what I have been using an obscene amount of automations to control.

What I would like to be able to do though is when I'm using sleep mode, I'd like to be able to control how much (or little) the sleep entities turn on - for example, in my boy's rooms, I like to leave their lamps on at 1% while they are asleep, and then have them turn off when it's sunrise. 

Is there anyway I can achieve this while still leveraging your component or am I going to have to go back to automations for that stuff?

**Comment by jseidl** [comment]
Hi @Backslashh, 

This is a little out of the scope of this component as there's some other very nice components such as [Adaptive Lighting](https://github.com/basnijholt/adaptive-lighting) and [Circadian Lighting](https://github.com/claytonjn/hass-circadian_lighting) that focus on managing light parameters. These integrations indeed pair perfectly with Magic Areas, hope that helps!

**Comment by Backslashh** [comment]
Thanks mate. Shortly after I opened the ticket I setup adaptive lighting. Holy crap I think I'm in love. 😍

Thank you for this component. I'm going to enjoy removing all my automations now!
