### ISSUE TITLE
Disable state isn't respected

### ISSUE THREAD

**Issue by sti0** [jseidl/hass-magic_areas#45]
Just for the sake of completeness:

As mentioned in https://github.com/jseidl/hass-magic_areas/pull/43 the `disable_state` isn't respected in case of turning lights on / off. 

https://github.com/jseidl/hass-magic_areas/blob/b963b919c157270cb28275310885f63ac7af831d/custom_components/magic_areas/binary_sensor.py#L298

**Comment by KTibow** [comment]
Want to make a quick PR? Just go to the file on the main branch, and press the edit button.
