### ISSUE TITLE
Switches?

### ISSUE THREAD

**Issue by seanmoro** [jseidl/hass-magic_areas#5]
Seems this will only turn on/off "light" entities.  "switches" do not seem to work.  Am I missing something?  I have a number of rooms that use smart switches to control dumb lights.  I would very much like to turn those off as well.

**Comment by jseidl** [comment]
@seanmoro indeed Magic Areas will only work with `light` domain but I got your back on this! I have the same situation. What I do is that I create a [Template Light](https://www.home-assistant.io/integrations/light.template/) and make those control the switch.

Hope that helps!
