### ISSUE TITLE
Temperature Sensor Aggregation is not working right

### ISSUE THREAD

**Issue by tyme2tb** [jseidl/hass-magic_areas#51]
I currently only have 1 sensor in each location that has temperature. Every single one of the aggregation sensors is showing way higher than it should.

Examples would be
livingroom:
![image](https://user-images.githubusercontent.com/4681426/99892865-b2437e80-2c47-11eb-98c0-6d91518b5bdb.png)

kitchen:
![image](https://user-images.githubusercontent.com/4681426/99892871-d30bd400-2c47-11eb-91c8-049563bbeb7c.png)

I have the 1.1.0 version installed

**Comment by KTibow** [comment]
Might be related to calcius to farenheit conversion, can you check for that?

**Comment by tyme2tb** [comment]
> 
> 
> Might be related to Celsius to Fahrenheit conversion, can you check for that?

Not sure how I would check that. Home assistant shows both as Fahrenheit as shown in the images above.

On that note it looks like the aggregation temp is converting my Fahrenheit temp as if it is Celsius to Fahrenheit as if it is Celsius, At least that is what math shows, but I have no idea how to figure out why Magic Areas is doing that.

**Comment by KTibow** [comment]
May be a duplicate, look at closed issues.

**Comment by tyme2tb** [comment]
It might be the same issue as a closed one, since it looks the same, but not sure how it would be a home assistant thing. Although not sure how it all works, so I guess it is possible.
https://github.com/jseidl/hass-magic_areas/issues/9

**Comment by tyme2tb** [comment]
I was just looking through some things. Does the aggregat sensor not set a Type of temperature? Another words it does not set it as F or C. If that is the case it looks like there is a chance Home Assistant converts it. Pasted a link below to something that could be the answer, but not a way to fix it.
https://github.com/home-assistant/core/issues/29595#issuecomment-562984205

**Comment by jseidl** [comment]
This is a weird issue since Magic Areas does set the `unit_of_measurement` property to the same of the sensors it reads from. Can you see on developer tools if `unit_of_measurement` is set?

**Comment by tyme2tb** [comment]
Not sure what you mean by developer tools.

**Comment by jseidl** [comment]
It's on the UI menu. Where you can see all the information about an entity. https://www.home-assistant.io/docs/tools/dev-tools/

**Comment by tyme2tb** [comment]
Yeah, I checked it shows it set to F also, so I am not sure where this is all happening, but the problem is I don't know what is going on in the backend. All I can see is the final result that is shown in HA, so even though it shows as F in HA that is because HA converts everything to F, so looking at the value in the Dev tool actually doesn't help.

Thanks, for an idea on something to check.

**Comment by JakeHertenstein** [comment]
Also seeing this issue. Could be related to #53? I suspect Deconz is doing some unit conversion under the hood and may lead to problems similar to not following `customize`. I've notice that some of my sensors were showing up in history graphs as Celsius despite the unit_of_measurement showing Farenheight in developer tools.

**Comment by jseidl** [comment]
That could be related.

**Comment by jseidl** [comment]
Possibly being fixed with the rework on #74. Will circle back after 2.0.0 is out to see if this is actually fixed.

**Comment by jseidl** [comment]
Possibly fixed by #74, released on [2.0.0](https://github.com/jseidl/hass-magic_areas/releases/tag/v2.0.0).

Please test it out and let me know if that solves it

**Comment by tyme2tb** [comment]
This does appear to work fine now. I have 2.0.4 installed
