### ISSUE TITLE
Switch entities should be able to serve as presence or light entities

### ISSUE THREAD

**Issue by syphernl** [jseidl/hass-magic_areas#56]
For instance, my computer (the `wol` entity) can be `on` or `off`. 

Same for a bunch of Zwave light switches which are in the `switch` domain instead of the `light` domain, since they can only turn on or off.

Adding these to `included_devices` doesn't seem to be doing anything.

**Comment by jseidl** [comment]
This is something I've been working on. Also `cover` devices would be interesting for garage doors.

**Comment by jseidl** [comment]
Since it's hard to tell the purpose of a `switch`, please https://www.home-assistant.io/integrations/light.switch/ instead.

**Comment by syphernl** [comment]
For the zwave switches that probably makes sense, but for other things (e.g. the `wol`) having a `light` entity doesn't make much sense to me IMHO.

**Comment by jseidl** [comment]
For the `wol`, you'd use a https://www.home-assistant.io/integrations/binary_sensor.template/ with the state of the switch. Add the `device_class` of `presence` and add it to the area, should work!
