### ISSUE TITLE
Logs full of warnings

### ISSUE THREAD

**Issue by andyinno** [jseidl/hass-magic_areas#8]
Just added the custom component,
As soon as I restarted home assistant the log is full of warnings like this:
[custom_components.magic_areas.sensor] Non-numeric sensor value (could not convert string to float: 'unknown')

Those warnings are related to components added by the web ui.
Would be nice to have unknown converted to safe values.

**Comment by jseidl** [comment]
This is a somewhat expected behavior. These warnings come from the aggregation sensors. Aggregation cannot summarize data from unknown states so it skips them. As soon these sensors are back they'll be accounted again. Maybe shouldn't be a warning just an info

**Comment by andyinno** [comment]
Yes, I know why it is caused.
I  just think that if a sensor is "unknown" should be skipped and maybe re-evaluated after a complete startup
It is happening during home assistant startup, therefore some value could be not available.

**Comment by jseidl** [comment]
It gets evaluated on startup and on state change of any of that areas sensors of the same device class and indeed is skipped. I'll downgrade the log level to info/debug.
