### ISSUE TITLE
2.0.0: Error while setting up magic_areas platform for sensor

### ISSUE THREAD

**Issue by klatka** [jseidl/hass-magic_areas#80]
I have updated magic_areas to 2.0.0.

In the configuration i deleted everything related to magic_areas and only added `magic_areas:`

After a restart Magic Areas appears in the Integrations page with the right areas but no specific sensor has been created (Area temperature and so on, even if i edit the config through UI). Only the general area binary sensors and presence hold switches are there.

2 bad log entries are appearing:
```
Logger: homeassistant.components.sensor
Source: custom_components/magic_areas/sensor.py:54
Integration: Sensor (documentation, issues)
First occurred: 16:22:35 (1 occurrences)
Last logged: 16:22:35

Error while setting up magic_areas platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/magic_areas/sensor.py", line 32, in async_setup_entry
    await load_sensors(hass, async_add_entities, area)
  File "/config/custom_components/magic_areas/sensor.py", line 54, in load_sensors
    map_key = f"{entity['device_class']}/{entity['unit_of_measurement']}"
KeyError: 'unit_of_measurement'
```

```
Logger: homeassistant
Source: custom_components/magic_areas/base.py:377
First occurred: 16:22:35 (2 occurrences)
Last logged: 16:22:35

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/magic_areas/base.py", line 496, in initialize
    await self.load_entities()
  File "/config/custom_components/magic_areas/base.py", line 532, in load_entities
    self.load_entity_list(entity_list)
  File "/config/custom_components/magic_areas/base.py", line 377, in load_entity_list
    unique_entities = set(entity_list)
TypeError: unhashable type: 'list'
```

**Comment by KTibow** [comment]
It needs a unit of measurement on one of your sensors. You can set that via HA customize.

**Comment by KTibow** [comment]
As for the second error, one of the entities in your list is a list instead of a int, float, decimal, complex, bool, string, tuple, range, frozenset, or bytes.

**Comment by KTibow** [comment]
Could you share your config?

**Comment by klatka** [comment]
I removed all sensors that relies on non existent magic area sensors e.g. average interior temperature and so on but still the same log entries are showing up...

I have around 300 entities, how to check which is missing an unit of measurement?



> As for the second error, one of the entities in your list is a list instead of a int, float, decimal, complex, bool, string, tuple, range, frozenset, or bytes.

Please tell me which list you mean? All entities of devices (50) that are assigned to areas (9)?

**Comment by TheArcturian** [comment]
I get the same "unit_of_measurement" errors in my log. I guess it is a bug.

**Comment by KTibow** [comment]
> I have around 300 entities, how to check which is missing an unit of measurement?

Try going into devtools, and type `unit_of_measurement` into the text field under Attributes. Make a new tab, and totally uncheck the attributes there. You can look for the difference.

> Please tell me which list you mean? All entities of devices (50) that are assigned to areas (9)?

You can't do anything about that error. You may want to edit this issue to remove that, and create a new bug report.

**Comment by jseidl** [comment]
Pushing a new minor release adding error checking and logging for entities missing `unit_of_measurement`. The `TypeError: unhashable type: 'list'` is probably due a bad `include_entities` configuration. Added a check for that as well.

**Comment by jseidl** [comment]
All the errors shall be fixed now on 2.0.1. They now throw warnings that shall help us identify entities missing `device_class` and `unit_of_measurement`. Please reopen if the problem persists.

**Comment by klatka** [comment]
> As for the second error, one of the entities in your list is a list instead of a int, float, decimal, complex, bool, string, tuple, range, frozenset, or bytes.

I went trough all entities but didn't found any list as state. What about input_select entities? They have options as a list but saved as attribute?

**Comment by jseidl** [comment]
MagicAreas will throw a warning if this happens again. `input_select` entities are not handled by magic_areas. Only `sensor`, `binary_sensor`, `climate`, `media_player` and `light` devices.

**Comment by klatka** [comment]
> Pushing a new minor release adding error checking and logging for entities missing `unit_of_measurement`. The `TypeError: unhashable type: 'list'` is probably due a bad `include_entities` configuration. Added a check for that as well.

I still have this error after update to 2.0.1

> All the errors shall be fixed now on 2.0.1. They now throw warnings that shall help us identify entities missing `device_class` and `unit_of_measurement`. Please reopen if the problem persists.

What about entities with `device_class` but without `unit_of_measurement`?

```
Entity sensor.echo1_next_alarm does not have unit_of_measurement defined
Entity sensor.echo1_next_timer does not have unit_of_measurement defined
Entity sensor.echo1_next_reminder does not have unit_of_measurement defined
```

This entity is from Alexa media player integration and it has `device_class: timestamp`
None of my other echo speakers is shown in log only the first. Has magic_areas stopped to look for other missing unit_of_measurement entities?

The update 2.0.1 still doesn't work for me as no sensor is getting created through magic_areas no matter what I set in the options.

**Comment by jseidl** [comment]
> What about entities with device_class but without unit_of_measurement?

You have to use [customize ](https://www.home-assistant.io/docs/configuration/customizing-devices/)to add the `unit_of_measurement` to those entities.

> None of my other echo speakers is shown in log only the first. Has magic_areas stopped to look for other missing unit_of_measurement entities?

Hard to tell, does these `echoN_next_alarm_*` entities exists for all alexa devices? Do all of them lack `unit_of_measurement`?

**Comment by klatka** [comment]
> You have to use [customize ](https://www.home-assistant.io/docs/configuration/customizing-devices/)to add the `unit_of_measurement` to those entities.

So let me understand, these requirements must be met:

1. All `binary_sensor` entities need to have a `device_class`.
2. All `sensor` entities need to have an `unit_of_measurement`. The `device_class` attribute is unnecessary and will be ignored.


> Hard to tell, does these `echoN_next_alarm_*` entities exists for all alexa devices? Do all of them lack `unit_of_measurement`?

Yes, all active Alexa speaker has these three timestamp entities and lack  `unit_of_measurement`.

**Comment by jseidl** [comment]
> All sensor entities need to have an unit_of_measurement. The device_class attribute is unnecessary and will be ignored.

Both `binary_sensor` and `sensor` entities need `device_class`. This is how MagicAreas figures out what are their purpose and how to aggregate them. `sensor` entities need `unit_of_measurement` in addition to `device_class` since this is also used for aggregations (we can't aggregate sensors of the same `device_class` that have different `unit_of_measurement`)

Yes, all active Alexa speaker has these three timestamp entities and lack unit_of_measurement.

Can you check if the `binary_sensor.area_XYZ` list those Alexa media_player entities under `presence_sensors`? If they're there then MagicAreas is recognizing the device itself. Those entities have text-states (timestamps) and won't be aggregated anyway (we can only aggregate numeric values) so you can safely ignore those warnings.

**Comment by klatka** [comment]
Okay, thank you for the clarification. :)

I will update the `unit_of_measurement`/`device_class` of the entities which MagicAreas need to use.


> Can you check if the `binary_sensor.area_XYZ` list those Alexa media_player entities under `presence_sensors`?

Yes, the Alexa speakers are correctly listed under `presence_sensors`. I will ignore the warnings.

Only this error is left:
```
Logger: homeassistant
Source: custom_components/magic_areas/base.py:377
First occurred: 16:22:35 (2 occurrences)
Last logged: 16:22:35

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/magic_areas/base.py", line 496, in initialize
    await self.load_entities()
  File "/config/custom_components/magic_areas/base.py", line 532, in load_entities
    self.load_entity_list(entity_list)
  File "/config/custom_components/magic_areas/base.py", line 377, in load_entity_list
    unique_entities = set(entity_list)
TypeError: unhashable type: 'list'
```

I think because of this error MagicAreas stopped working and won't create new entities for areas.

**Comment by jseidl** [comment]
> I think because of this error MagicAreas stopped working and won't create new entities for areas.

Can you please update to `2.0.2`? Added some code that should deal gracefully with this error and throw warnings instead of crashing.

**Comment by klatka** [comment]
With update `2.0.2` MagicAreas is finally working for me. :)

I got this warning in the log:

`Logger: custom_components.magic_areas.base
Source: custom_components/magic_areas/base.py:531
Integration: Magic Areas (documentation, issues)
First occurred: 0:52:28 (2 occurrences)
Last logged: 0:52:28
Entity ID is not a string: ['light.ankleidelampe']`

**Comment by jseidl** [comment]
> ['light.ankleidelampe'] I don't know why it is not recognized as a string.

It's a 1-element list with the string.

Did you specified it in `include_entities` by any chance?

**Comment by klatka** [comment]
> > ['light.ankleidelampe'] I don't know why it is not recognized as a string.
> 
> It's a 1-element list with the string.
> 
> Did you specified it in `include_entities` by any chance?

So there is the list from the first log entry. I don't have this lamp in any `include_entities` section.

**Comment by jseidl** [comment]
> But the area specific entities like area_temperature_x has not been created. Only the global and interior/exterior ones.

Did you enable the `aggregates` feature for those areas? Also you need to configure the `aggreagtes_min_entities` value accordingly.

> So there is the list from the first log entry. I don't have this lamp in any include_entities section.

Can you post the binary_sensor attributes for the area where this offending light resides?

**Comment by klatka** [comment]
Attributes of `binary_sensor.area_ankleide`:

```
presence_sensors:
  - media_player.echo1
  - switch.area_presence_hold_ankleide
features:
  - aggregates
  - light_groups
active_sensors: []
lights:
  - light.ankleidelampe
clear_timeout: 60
update_interval: 60
type: interior
climate:
  - climate.thermostat_ankleide
on_states:
  - 'on'
  - home
  - playing
  - open
automatic_lights: disabled
night: false
sleep: false
friendly_name: Area (Ankleide)
icon: 'mdi:texture-box'
device_class: occupancy
```

> Did you enable the `aggregates` feature for those areas? Also you need to configure the `aggreagtes_min_entities` value accordingly.

My mistake :)

**Comment by jseidl** [comment]
Hmmm seems like the light `light.ankleidelampe` is detected even thou the warning is thrown. Is anything not working?

**Comment by klatka** [comment]
It seems like everything is working. Thank you 👍🏻

**Comment by Bodge-IT** [comment]
Hi @jseidl sorry to comment on a closed issue but should I be getting this error on the latest beta?
```
Logger: homeassistant.components.binary_sensor
Source: custom_components/magic_areas/binary_sensor.py:223
Integration: Binary Sensor (documentation, issues)
First occurred: 20:58:04 (6 occurrences)
Last logged: 20:58:04

    Error adding entities for domain binary_sensor with platform magic_areas
    Error while setting up magic_areas platform for binary_sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 613, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 747, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/magic_areas/binary_sensor.py", line 265, in async_added_to_hass
    await self._initialize()
  File "/config/custom_components/magic_areas/binary_sensor.py", line 290, in _initialize
    self.load_attributes()
  File "/config/custom_components/magic_areas/binary_sensor.py", line 223, in load_attributes
    for feature_name, opts in self.area.config.get(
AttributeError: 'list' object has no attribute 'items'
```

A slight correction to a point made above... a binary sensor does not need to have a device_class set.
`None: Generic on/off. This is the default and doesn’t need to be set.`

I wondered if it was because I had created an include to binarys.yaml in my config, instead of binary_sensors.yaml?
Changing the name doesn't seem to have fixed my issue.
