### ISSUE TITLE
2.0.x: config flow fails with Aborted

### ISSUE THREAD

**Issue by syphernl** [jseidl/hass-magic_areas#85]
After installing 2.0.0 _without_ having `magic_areas:` in my config the onboard would throw an error about missing config. 

After adding this and restarting the onboard now simply shows "Aborted" whenever I select a area. Strangely, nothing is being logged as to why this happens.

**Comment by jseidl** [comment]
Just to confirm, you added the magic_areas config entry on yaml and restarted HA?

**Comment by syphernl** [comment]
Yes the `magic_areas:` line is in configuration.yaml.

When I enable debug logging for this component I am not seeing anything during onboard but it is showing a whole bunch of "sensor xyz changed state to on/off" etc.

**Comment by jseidl** [comment]
Does the area `binary_sensors` get created?

**Comment by syphernl** [comment]
No areas (besides the ones already in there) are being created af all. The error occurs when I go to integrations > add integration > magic areas > selecting an area  > submit.

**Comment by jseidl** [comment]
You don't need to add the integration. It should show up already on your integrations page with the areas loaded.

This onboard code is leftover, I'll remove-it and add a descriptive note to avoid this confusion

**Comment by jseidl** [comment]
Please reopen this if you still have issues.
