### ISSUE TITLE
Area Temperatures converting temps in F to temps in F

### ISSUE THREAD

**Issue by lonejeeper** [jseidl/hass-magic_areas#9]
Bathroom sensor reports 68.5 degrees, area sensor lists temp at 155.3, referencing said bathroom sensor.  The math works out that the area sensor is redoing the conversion to F. (68.5°C × 9/5) + 32 = 155.3°F

**Comment by jseidl** [comment]
That shouldn't happen since values are averaged as is. Will look into it. Can you provide more information such as your magic areas configuration?

**Comment by lonejeeper** [comment]
Sure:  I've just gotten started with this, so things are very basic.  Installed via HACS.
```
    bath_guest:
        include_entities:
          - binary_sensor.guest_bath_motion 
```

This entity is a binary sensor from a template.    It is also doing an average for areas with multiple sensors, but the value given is the ([average of sensor values] × 9/5) + 32.

Thanks for your help, I really like what this can do!

**Comment by jseidl** [comment]
Can you provide a screenshot with the attributes (dev tools state view) for this areas temperature sensors?

**Comment by lonejeeper** [comment]
![image](https://user-images.githubusercontent.com/56227791/96631222-09ba9b80-12e4-11eb-89f4-7a4693a2a808.png)
![image](https://user-images.githubusercontent.com/56227791/96631315-27880080-12e4-11eb-9c0d-a5625abfd3ee.png)

The area seems to be using something other than what I'd configured, which I'm not sure I understand, but the end result is the same.

**Comment by jseidl** [comment]
That's weird because MA doesn't do any conversion. Just averages it.

Does your setup uses `metric` or `imperial`?

```
homeassistant:
  unit_system: imperial
```

If you have it on `metric`, HA will assume values are in C and the unit of measurement to F will force the conversion.

**Comment by lonejeeper** [comment]
Yep, I'm on imperial.

I've expanded the magic areas out to the rest of my areas and temperature is consistently re-converted to F, so it's at least  consistent.

I couldn't find where any math was done to convert anything in your code either (I figured I just missed it somewhere). 
I do already have a separate room aggregate/average temperature template, so this isn't needed but would have been nice, maybe I'll add some math to convert it back.

Thanks!

**Comment by jseidl** [comment]
This issue has been intriguing me a lot. My code doesn't do any math, just call `mean` on the values and repasses the unit of measurement. It works well in my prod setup and my dev box. Both are in F.

This conversion is being done by Home Assistant and not the component. Converting it back would only mask the problem. Needs additionial digging to pinpoint what's wrong.

**Comment by lonejeeper** [comment]
I don't believe this is your problem any longer though, you may close this.   I will start a thread in the homeassistant forums and see what can be found from there.  This issue rapidly went beyond my abilities to troubleshoot.

Thanks!
