### ISSUE TITLE
Consider device_class: connectivity as presence sensor

### ISSUE THREAD

**Issue by klatka** [jseidl/hass-magic_areas#91]
I have a ping sensor for my PC which I want to use as presence sensor for my office room.

In the YAML configuration I had the following config:

```
  presence_sensor_device_class:
    - "connectivity"
    - "motion"
    - "occupancy"
    - "presence"
```

In the UI I can not select `connectivity` as presence sensor class.

**Comment by jseidl** [comment]
Closed by #99. Coming up in next release.
