### ISSUE TITLE
Adopt excluded_entities in area_interior, area_exterior and area_global

### ISSUE THREAD

**Issue by klatka** [jseidl/hass-magic_areas#93]
For me, it is much overhead if I have to exclude all entities in the global areas after I exclude them in a specific area.

For example, I exclude a binary sensor of a tablet running HA Android app in its associated area (interior type) that is recognized as a presence sensor. I except that this entity is automatically excluded in `area_interior` and `area_global`.

Is it possible to adopt the `excluded_entities`?

Edit: The entity I mentioned above is actually `binary_sensor.hometablet_gerat_ist_gesperrt` from the Android app. It doesn't have a device_class attribute:
```
friendly_name: HomeTablet Gerät ist gesperrt
icon: 'mdi:cellphone-lock'
```

I don't know why it is even recognized as a presence sensor.

**Comment by jseidl** [comment]
This should be the case. Meta areas probe the area's entities AFTER exclude and include (supposedly). Will look into it

**Comment by klatka** [comment]
Okay, after restarting HA the excluded_entities are adopted. Because the other options are applied immediately to the areas and meta areas I thought the adoption applies immediately too.

Maybe there could be some clarification like in #80 added into README.md :)

**Comment by jseidl** [comment]
When you save options for one area it should reload all Meta areas. Will investigate
