### ISSUE TITLE
Feature request: change aggregate names

### ISSUE THREAD

**Issue by Anian-igor** [jseidl/hass-magic_areas#96]
Maybe will be good to change aggragate name from "Area Illuminance [lx] (Living)"  to "Area Illuminance (Living)" for better look?

**Comment by jseidl** [comment]
You can rename the entity on the UI. I need to include the unit of measurement to differentiate between `device_class` that are the same but with different unit of measurement. (i.e. `power` has `W`, `kWh`, `V` and `A` as possible unit of measurements).

One could argue that I could only add the unit of measurement if there's more than one, but if sometime in the future you happen to have one, all your related entities would be created with the new name (with unit of measurement) and you'd end up with orphan entities and automations with dead triggers.

**Comment by KTibow** [comment]
How about always setting the entity ID to include the unit of measurement, but only setting the friendly name if there's more than one?

**Comment by jseidl** [comment]
That could work. I need to see how to override the `entity_id` (shouldn't be difficult) since currently is being derived from the `friendly_name`
