### ISSUE TITLE
zigbee2mqtt light update considered as motion

### ISSUE THREAD

**Issue by andyinno** [jseidl/hass-magic_areas#97]
I have a bulk of philips hue and ikea lights, they are connected to Home Assistant via zigbee2mqtt.

Zigbee2mqtt exports the OTA update binary_sensor indicating that a new firmware is available.
I need to explicit remove the binary_sensor otherwise if a new update is available it activates the presence in the area.

A single light expose to home assistant:

- light state 
- link quality
- update_state (on/off)
- update_state

**Comment by jseidl** [comment]
What's the `device_class` of this sensor that is being picked up?

**Comment by andyinno** [comment]
Hi!
sorry for my late reply,

the device class is not set by me in the configuration. z2mqtt does not set a device class because the autoconfiguration transfer multiple entities for every device (status, command, update_state, signal_strength, etc)

That was the issue for why I installed the magic areas it won't work. The fact is that some entities that I added to the areas was always active.

**Comment by jseidl** [comment]
Can you try adding a `device_class` to this entities through [customize](https://www.home-assistant.io/docs/configuration/customizing-devices/)?

**Comment by andyinno** [comment]
Yes, I did it for a room and it is working, however, customizing each sensor on large z2m network is a real PITA.

I fear that the manual exclusion is the only option for it now.
Could be this a nice note to add to the documentation? I think that other issue that was opened with "magic areas" won't work for my lights was hit by some of those other sensor that are ON

**Comment by jseidl** [comment]
Unfortunately the whole "Magic" aspect of Magic Areas relies heavily on the device class. It is a shame that z2m doesn't provide this info.

I'm working on adding some proper documentation because the current one is way outdated and overall lackluster. 

Can you clarify your other issue? I didn't quite understood.

**Comment by andyinno** [comment]
hi!
sorry my fault. I am not an English native speaker.

What I meant was that when you published the transition to flow configuration, I saw a lot of issues complaining that the lights won't turn on or off. I think zigbee2mqtt is widely used and therefore a lot of people could hit this. If a device reports a firmware update and the firmware update entity is not filtered out, automatic lights stops working. Stops working because a sensor is always active.

**Comment by jseidl** [comment]
Gotcha, which `device_class` is the firmware update sensor?

**Comment by Patrick1610** [comment]
Hi, I am experiencing the same and currently have to exclude the update status from each Area, like this: 
![image](https://user-images.githubusercontent.com/6585375/117447252-8be77600-af3d-11eb-9f0a-f423c9c22cd5.png)
The strange thing is that it seems to behave as occupancy / motion / door sensor, since as you can see, that is the only sensors I have activated. 
Is there a solution possible @jseidl? Maybe even by adding a setting to exclude all update_available sensors from all Areas? 
If you need more info let me know, I'll see what I can find out.

**Comment by jseidl** [comment]
Hi @Patrick1610 , can you paste me the entity attributes for this `update_available` sensor? Not sure if this is an easy fix as this is an integration-specific entity. I'm assuming is on the device_class of `presence`. Why is this sensor popping up in all areas? Can you check which area is this sensor added on HA?

**Comment by Patrick1610** [comment]
Okay, I have to admit I'm pretty new to Home Assistant, so forgive me if this is not the info you mentioned, but here's all the information I can find about an active OTA state. 

Luckily it is not popping up in all areas. But this outlet for example: if I add the device to my living room, the entity 'update available' will keep the living room magic area active. 

![Screenshot 2021-05-08 at 12 04 27](https://user-images.githubusercontent.com/6585375/117535389-d62c2e00-aff5-11eb-9aa5-68d70ae83f76.png)
![Screenshot 2021-05-08 at 12 04 47](https://user-images.githubusercontent.com/6585375/117535390-d6c4c480-aff5-11eb-8677-4c74114d930d.png)
![Screenshot 2021-05-08 at 12 05 12](https://user-images.githubusercontent.com/6585375/117535391-d6c4c480-aff5-11eb-8453-b956d975bfe3.png)
![Screenshot 2021-05-08 at 12 05 23](https://user-images.githubusercontent.com/6585375/117535392-d75d5b00-aff5-11eb-94a6-141973edcbf0.png)
![Screenshot 2021-05-08 at 12 05 45](https://user-images.githubusercontent.com/6585375/117535393-d75d5b00-aff5-11eb-9f7f-2be9d088a8fc.png)
![Screenshot 2021-05-08 at 12 05 56](https://user-images.githubusercontent.com/6585375/117535394-d75d5b00-aff5-11eb-948d-62edfd58fec8.png)
![Screenshot 2021-05-08 at 12 06 08](https://user-images.githubusercontent.com/6585375/117535395-d7f5f180-aff5-11eb-9a61-f694377fe982.png)

**Comment by andyinno** [comment]
Sorry if I did not reply to the issue,

from my understanding it comes without a device_class.
During my initial tests I tried to manually set the device class but I did not find any device_class usable for the update state.

Then I just filtered out the state.

In order to comment about this:

>Luckily it is not popping up in all areas.

It is based on which integration you are using and which attribute the entity exposes.
In my example I am using a couple of Ikea lamps and a lot of philips lamps. Also some chinese adapters. The chinese adapters do not support OTA, therefore the sensor is not exported by zigbee2mqtt.

Here: https://github.com/Koenkk/zigbee2mqtt/issues/882 is an issue where someone asks to add device_class to the autodiscovery fields. The problem is that a device can export many fields, therefore the autodiscovery could not be overridden in this way.

this https://www.zigbee2mqtt.io/devices/9290024406.html is an example of a device that support the OTA update.
With mqtt autodiscovery ON the entity is automatically imported in home assistant. 

The 2 entity that are imported in home assistant are:

- update_available
- update_state

The first, tells if an OTA is available and can be performed, the last tells if the OTA is running.

**Comment by jseidl** [comment]
This is a problem I have with other devices in my house. I have a couple of sensors which `device_class` is `presence` and gets picked up by MA as well. The only way of excluding them is by adding them to the include list.

There's no way to discern between a bogus `presence` sensor unfortunately
